TEAM-DAWM/SHELLIN-CLIENT

yarn.lock

pr 풀받으신 후 yarn install 잘 되는지 확인해주세요!
close #10

[FIX] update yarn checksums

---

yarn.lock

yarn.lock 파일을 재생성해 checksum 맞췄습니다
정상 배포되었습니다!
왜 로컬환경에서는 yarn build 로 잘 빌드되는데 배포 환경에서는 build시 Integrity check fail이 났는지 잘 모르겠습니다
close #15

[FIX] 배포 Integrity check fail

---

package.json
src/App.tsx
src/Router.tsx
src/pages/Calendar.tsx
src/pages/Calender.tsx
src/pages/DashBoard.tsx
src/pages/Login.tsx
src/pages/NotFound.tsx
src/pages/Setting.tsx
src/pages/Today.tsx
yarn.lock

- react-router-dom 설치
- Router.tsx 생성
- login, today, dashboard, calender, setting 페이지 추가
```tsx
<BrowserRouter>
<Routes>
<Route path="/" element={<Login />} />
<Route path="/today" element={<Today />} />
<Route path="/dashboard" element={<DashBoard />} />
<Route path="/calendar" element={<Calendar />} />
<Route path="/setting" element={<Setting />} />
<Route path="/*" element={<NotFound />} />
</Routes>
</BrowserRouter>
```
로 /today, /dashboard, /calendar, /setting 으로 각 페이지 이동 가능합니다
기본화면은 로그인 페이지로 되어 있습니다!
없는 페이지 접근시 `NotFound` 컴포넌트 뜨도록 해뒀습니다
close #23

[INIT] 라우팅 설정

---

src/components/common/modal/Modal.tsx
src/components/common/modal/ModalHeaderBtn.tsx
src/components/common/modal/ModalTextInputTime.tsx
src/components/common/modal/TextInputBox.tsx
src/components/common/textbox/TextInputDesc.tsx
src/components/common/textbox/TextInputTime.tsx
src/components/common/textbox/TextInputTitle.tsx

- 공통 모달 퍼블리싱을 하였습니다.
- 아직 진행중인 컴포넌트는 다른 컴포넌트로 대체하여 작성하였습니다.
> 기록하며 개발하기!
- `box-sizing: border-box;`를 사용하면 padding이 안쪽으로 생기는군요 저는 몰라서 width에서 padding 빼고 설정하고 했는데 이거 하니 아주 편합니다.
- 모달이 2개 뿐이라서 승연이가 만들어 놓은 sizeType을 사용하여 구분하였습니다. 사실 확장성을 생각하면 좋지 않은 것 같아서 모달 구조에 대해서 더 좋은 방안이 생각나시면 말씀해주세요!!! 젭알
close #35

[FEAT] 공통 모달 퍼블리싱

---

src/components/common/button/textBtn/TextBtn.tsx
src/components/common/button/textBtn/textBtnStyle.ts

- 긴히 쓸 일이 있어용
- width, height로 설정한 버튼 크기를 마진 값으로 수정했습니다! 다른 페이지에서 길게 쓰이더라구요,,,,
> 기록하며 개발하기!
- 단순 뷰작업이라 딱히 없습니다.
- 재사용되는 공통 컴포넌트를 구현하기 전에 어떤 뷰에서 어떻게 쓰이는지 잘 확인해보자 외에느,,,,
- 단순 뷰작업이라 딱히 없습니다.
- 피드백 았다면 부탁듸=립
close #87

[FIX] 공통 컴포넌트 text btn 크기 수정

---

src/components/common/NavBar.tsx

- z-index 값 2로 먹임
- 배경색 흰색 깔아둠
> 기록하며 개발하기!
- 간단한 뷰 작업이라 딱히 없습니다!
- 간단한 뷰 작업이라 딱히 없습니당
- z - index는 2로 주었는데, 혹시 다른 곳에서 z-index 값 먹이실 분 계시면 이거 참고해서 주세용-!
close #83
`프라블럼(kpt 회고 ㅋㅋ)`
https://github.com/TEAM-DAWM/NUTSHELL-FE/assets/151596186/f5edb5ce-6e26-4c75-b370-d201660e2cf6
`트라이(kpt 회고 ㅋㅋ)`
https://github.com/TEAM-DAWM/NUTSHELL-FE/assets/151596186/be238857-4614-4f37-ada4-ef568918c580

[FIX] nav bar 우선 순위 및 배경색 조정

---

src/components/calendarPage/miniCalendar/MiniCalendar.tsx
src/components/calendarPage/miniCalendar/MiniCalendarHeader.tsx
src/components/calendarPage/miniCalendar/MiniCalendarStyle.tsx
src/components/targetArea/TargetAreaDate.tsx
src/pages/Calendar.tsx
src/utils/getToday.ts

- 미니캘린더 만들었음
- 오늘의 year, month, day 를 반환하는 `getToday` 를 util 함수로 따로 뺐습니다.
미니캘린더 잘 되는지 봐주세용
close #94

[FEAT] 미니캘린더 제작

---

src/styles/GlobalStyle.tsx

- user-select: none;을 body에 추가하여 텍스트 드래그 방지를 하였습니다.
> 기록하며 개발하기!
- user-select: none;을 하면 텍스트 드래그 방지가 됨을 알게 되었습니다
- 호옥시 다른 곳에 더 필요한 부분 혹은 body에 넣으면 안된다면 말씀해주세요!
- body에  user-select: none;를 줘서 드래그앤 드랍에 문제가 생기려나??
close #133

[FEAT] 텍스트 드래그 방지

---

src/styles/GlobalStyle.tsx

버튼에 cursor pointer 값을 주었습니다.
본인 페이지 / 컴포넌트 확인해보시고 버튼 태그 아닌 필요한 곳에는 알아서 설정해서 쓰세요~~
> 기록하며 개발하기!
- 없듬
- 없듬
close #138

[FIX] GlobalStyle 버튼 커서 추가

---

.github/workflows/gradle.yaml

- gradle.yaml 파일에 .env setting 단계 추가
- 단계 순서 괜찮나요  ??
close #163

[FEAT] yaml 파일 env 변수추가

---

src/apis/tasks/getTask/query.ts
src/components/common/EmptyContainer.tsx
src/components/common/StagingArea/StagingAreaTaskContainer.tsx
src/components/targetArea/TargetTaskSection.tsx
src/constants/tasksToday.ts

- 뷰 구현 끝냈습니다. ;.... 마지막 퍼블리싱; ;; ㅅ죄송해요 ㅜ
- today의 staging과 target empty 뷰입니다.
- 확인해보고 싶으신 분은 상수 데이터에 TODAY를 data 대신 넣어주시면 되어용!!
> 기록하며 개발하기!
- 간단한 뷰 구현이라 딱히 없습니다.
- 승연이한테 isFetched를 빼고 대신 placeholder 상수 데이터를 넣어놓는 법을 배웠어요,, 내일 더 깊게 질문 해보도록 하겠습니다. 졸려서,, 더 듣고싶어요,,
- 하드코딩인지 봐주시면 감사하겠습니다.
close #177

[FEAT] today empty 뷰 퍼블리싱

---

src/pages/Today.tsx

- 태스크 클릭 후 캘린더 긁으면 UI 상 캘린더에 이벤트 생성되도록 수정했습니다,
close #195

[BUG] 태스크 클릭 후 이벤트 생성

---

src/apis/tasks/createTask/CreateTaskType.ts
src/apis/tasks/createTask/axios.ts
src/apis/tasks/createTask/query.ts
src/components/common/button/EnterBtn.tsx
src/components/common/datePicker/DateCorrectionModal.tsx
src/components/common/textbox/TextInputStaging.tsx

- 태스크 생성 연결
> 기록하며 개발하기!
-
- Today 페이지 서버 다운되면 터짐 에러처리 해야할듯
close #190

[FEAT] Task 생성 api 연결

---

src/constants/dashboardSummaryInfo.ts

- 이미지 경로 바꿔주었습니다
> 기록하며 개발하기!
- 없음. 
- 백번째 피알!
- 대시보드 뷰 이미지 렌더링 안되는거 저한테 다 들켰죠ㅏ,,
close #203 
이젠 잘 된다능

[FIX] 대시보드 뷰 이미지 경로 수정

---

src/apis/tasks/deleteTask/axios.ts
src/apis/tasks/deleteTask/query.ts
src/components/common/BtnTask/BtnTask.tsx
src/components/common/BtnTask/IconHoverContainer.tsx
src/components/common/StagingArea/StagingAreaTaskContainer.tsx
src/components/common/button/statusBtn/StatusStagingBtn.tsx
src/components/targetArea/TargetTaskSection.tsx
src/pages/Today.tsx

- 태스크 삭제 api 를 쓰레기통 버튼에 연결했습니다
- 지원언니가 BtnTask status 연결해주고 갔습니다. string 타입으로 바꿨습니다
- 잘되는지 봐주세요!
close #204

[FEAT] Task 삭제 api 연결

---

src/pages/Today.tsx

- 상태 업데이트 코드 제거
mutation 에서 invalidateQueries ..에서 쿼리키로 처리해주는 것 같아 해당 코드 제거했습니다
- task 를 받아오지 못해서 에러 발생하는 경우 data에 접근해서 터지는 상태였는데 error 판단해서 크기 잡아둔 `BtnTaskContainer` 스타일 컴포넌트가 렌더링되도록 설정했습니다
잘못 설정된 부분이나 이상한 부분 있으면 코리 달아주세요!
close #199

[FEAT] Today 페이지 정리

---

src/components/calendarPage/CategoryBox.tsx
src/components/common/fullCalendar/FullCalendarStyle.ts
src/pages/Login.tsx

- 로그인 시 개인정보, 이용약관 링크를 수정하였습니다.
- 풀캘린더 스크롤 디자인에 visibility: visible;를 추가하였습니다.
- 승연이 페이지에서 스크롤 스타일 잘 적용하는 지 확인 부탁드려용
close #225

[FIX] 캘린더 스크롤바 스타일 수정 & 이용약관 링크 수정

---

src/components/common/textbox/TextInputStaging.tsx

- tirm을 이용해서 좌우 공백이 없는 지를 확인해서 공백만 보내는 경우 api를 호출하지 못하게 하였습니다.
- 앤터키를 입력해서 일정 추가가 가능하도록 로직을 추가하였습니다.
> 기록하며 개발하기!
- onKeyDown를 통해서 키 입력을 받을 수 있음을 알게 되었습니다.
close #237

[FEAT] 일정 추가에서 로직 보완

---

src/components/common/modal/Modal.tsx

- Task 모달을 통한 삭제 api 연결
- Task 삭제 방식 중, 모달을 통한 삭제 api 연결
> 기록하며 개발하기!
-
- 삭제 확인 부탁드립니다!
close #240

[FEAT] Task 모달을 통한 삭제 api 연결

---

src/apis/tasks/editTask/EditTaskDescriptionType.ts
src/apis/tasks/editTask/axios.ts
src/apis/tasks/editTask/query.ts
src/components/common/BtnDate/BtnDate.tsx
src/components/common/BtnTask/BtnTask.tsx
src/components/common/modal/Modal.tsx
src/components/common/modal/TextInputBox.tsx
src/components/common/textbox/TextInputDesc.tsx
src/components/common/textbox/TextInputStaging.tsx
src/components/common/textbox/TextInputTitle.tsx
src/components/targetArea/TargetTaskSection.tsx

- Task 설명 수정 api 연결
> 기록하며 개발하기!
- querykey에 두가지 키가 들어가있는 경우 자동 렌더링이 되지 않아 제거하였습니다!
- 타입 통일 관리의 중요성을 알았습니다. date 관련 변수나 함수의 타입에 Date, string을 번갈아서 써서 타입 오류 해결에 시간이 많이 소요되었습니다.
- task 수정이 정상동작하는 지 확인 부탁드립니다.
close #213

[FEAT] Task 설명 수정 api 연결

---

src/components/common/textbox/TextInputStaging.tsx
src/types/textInputType.ts

- 마감기한설정 컴포넌트 UI 개선
> 기록하며 개발하기!
- 분기처리를 잘해두면 편하다.
- sizeType에 default 추가했습니다!
close #248

[REFACTOR] 마감기한설정 컴포넌트 UI 개선

---

README.md

- ex1) 로그인 시, 구글 소셜 로그인 기능을 추가했습니다.
- ex2
- ex3
> 기록하며 개발하기!
-
- ex2
close #issue_number

[HOTFIX] 리드미 개큰 업데이트

---

src/apis/tasks/updateTaskStatus/query.ts
src/components/common/BtnTask/BtnTask.tsx
src/components/common/StagingArea/StagingArea.tsx
src/components/common/StagingArea/StagingAreaTaskContainer.tsx
src/components/common/button/settingBtn/SettingCheckBtn.tsx
src/components/common/modal/Modal.tsx
src/components/common/modal/ModalHeaderBtn.tsx
src/pages/Today.tsx

- targetDate 관련 타입 오류 및 props 전달 오류 수정
- targetArea에서도 task 수정
> 기록하며 개발하기!
- 타입을 여러 번 바꾸기보다 새로운 props를 넘겨서 분기처리하는 방법도 있다. 간단하지만 생각을 못했던 부분이다. 해당 props가 안쓰이는 경우도 대처하기 위해 고려를 더 해봐야겠다.
- 에러가 수정되었는지 테스트 부탁드립니다!
close #265

[HOTFIX] Task 상세 조회 및 수정 관련 에러 해결

---

src/components/common/BtnDate/BtnDate.tsx
src/components/common/modal/Modal.tsx
src/utils/parseDate.ts

- 날짜 타입을 변경했습니다! date picker 모달에 이상한 형식으로 뿌려지는 이슈가 있었어서,, 
- 타입 선언 해줄 때 콘솔 잘 찍어보면 좋을 것 같습니다 ㅎㅎ
> 기록하며 개발하기!
-
- 확인해보시고 어푸해주세용
- 브랜치 이름 봐주세용
close #263

[FIX] 날짜 타입 변경

---

src/components/common/fullCalendar/FullCalendarStyle.ts

- 스타일 위치를 주말을 더 아래에 해서 주말 색상이 반영되도록하였습니다.
close #264

[FIX] 주말 색상 변경

---

src/styles/color.ts
src/styles/font.ts
src/styles/theme.ts

- theme에 color 추가 했습니다
- 아 폰트도
> 기록하며 개발하기!
- 생각보다 오래 개발을 쉬었구나...
- 새로운 디자인 시스템 색상은 color 파일에 빼두었고, 기존 색상은 palette 입니다! 에러 빠바방 뜰 것 같아서 우선 그대로 두었는데, 추후 제거하거나 의견 주시면 바로 제거할게요!
- 폰트는 아직 확정되지 않아서 우선 컴포넌트 작업 하시고, 확정 되면 추가해두겠습니다.
- _Grey1이 추가될 수 있습니다. 디자인 답변 받고 확정되면 반영해둘게요_ 레전드 그냥 안쓰인대요. 없는거로 알아주세요
- 이번에는 primary color가 아이콘/텍스트/버튼 등에 따라 달라서, 그냥 색상으로 입력해두는 게 편할 것 같아 따로 핵심 컬러 설정해두지 않았습니다.
- 아 그리고 이전에 작업하던 icon 이름 통일 작업이요... 수정하다 브랜치 안연지 두달이라 어디까지 수정했는지 헷갈리는데 유기해도 될까요? ㅜㅜ 이번에 작업할 땐 ic_name으로 통일하면 좋을 것 같아요 ㅎ ㅎ
**_폰트 추가했습니다._**
- 기존 구조와 다르게 코드를 간소화해보려고 했는데, 맘에 안들면 원복할테니 말해주세요.
**기존 코드 형식**
```
const fonts = {
PretendardBold: 'Pretendard-Bold',
PretendardSemiBold: 'Pretendard-SemiBold',
PretendardMedium: 'Pretendard-Medium',
PretendardRegular: 'Pretendard-Regular', …
```

[INIT] theme 색상 & 폰트 설정

---

.github/workflows/chromatic.yml
package.json
yarn.lock

- 스토리북을 배포했습니다
> 기록하며 개발하기!
- 그.. 밑에 댓글 기록을 보면 링크없는 댓글이 두개가 있는데요..
- `- ${{ steps.chromatic.outputs.storybookUrl }}` 을 yml 파일에서 사용하고 있는데, steps의 chromatic 의 아웃풋에 접근하기 때문에
- chromatic 이라는 이름으로 id를 붙여줘야 이 링크에 접근해서 출력 가능한 걸 알았습니다.  
다음과 같이 id 추가한 뒤 정상 작동 하였습니다.  
또 pr 에 댓글달기 위해서 write 권한이 필요해 야믈파일 permission 쪽에 해당 내용 추가했습니다.
- 배포링크 잘 들어가지는지, 밑에 Button 쪽 만들어둔 거 잘 보이는지
- 야믈파일 구성 괜찮은지 확인부탁드려욤
close #294

[DOCS] 스토리북 배포

---

src/styles/colorToken.ts
src/styles/font.ts
src/styles/theme.ts

- 피그마 시스템에 따라 **colorToken**을 theme에 새로 추가했습니다.
- font.ts에서 **font-weight**이 적용 안되는 부분 추가했습니다.
- font.ts에서 **font-family** 대체폰트 추가했습니다. (사파리에서 pretendard가 안먹음)
> 기록하며 개발하기!
-
- 중복되는 색상이 많지만 개발 편의를 위해 🥹🥹 colorToken 추가했습니다!
close #302

[STYLE] add color token

---

src/components/common/NavBar.tsx

- 사이드바 디자인을 변경했습니다
- 커밋 한개짜리라 가볍게 봐주세용
- 옆 섹션 여닫는 기능은 차후 옆섹션 만들때 추가하도록 하겠습니다
- 전이랑 화면크기가 다른 것 같은데, 이거 사이즈 맞추기 함 해야할 것 같아요
close #315

[FEAT] 사이드바 제작

---

src/components/DashboardPage/DashboardTask.tsx
src/components/common/BtnTask/BtnTask.tsx
src/components/common/BtnTaskContainer.tsx
src/components/common/NavBar.tsx
src/components/common/StagingArea/StagingArea.tsx
src/components/common/StagingArea/StagingAreaTaskContainer.tsx
src/components/common/modal/ModalArrange/ModalArrange.tsx
src/components/common/v2/taskBox/Todo.tsx
src/components/targetArea/TargetArea.tsx
src/components/targetArea/TargetTaskSection.tsx
src/pages/MainLayout.tsx
src/pages/Today.tsx
src/types/tasks/taskType.ts

- 덤핑에리아 디자인 수정,
- 기존 연결되었던 컴포넌트 중 필요없는 것 제거
- 타입 변경에 따른 hasDescription 필드를 TaskType 타입에서 제거
- 사이드바 위치 수정
- 전체 레이아웃 크기 조정
- 정렬 모달 위치까지는 설정해 두었는데, 쏟아내기 입력창 쪽 입력 모달은 연결 안 했습니다. 해당 부분 디자인 수정 완료되면 적용하겠습니다.
- 서버가 없어서 api로 정보 받아오던 부분 때문에 기존에는 투데이 페이지를 정상적으로 표시할 수 없어서, 샘플 데이터를 임시로 만들어 렌더링하도록 설정해 두었습니다.
close #317

[FEAT] DumpingArea 제작

---

src/components/common/v2/IconButton.tsx
src/components/common/v2/button/Button.tsx
src/stories/Common/Button/IconButton.stories.tsx

- 점 추가
- 버튼 보더 컬러 수정
- cursor pointer
close #326

[FEAT] 아이콘버튼 점 추가

---

index.html

[CHORE] maze 스크립트 제거

---

index.html
src/assets/images/index.ts
src/components/loginPage/GoogleLoginBtn.tsx
src/components/loginPage/LoginContainer.tsx
src/pages/Login.tsx
src/styles/color.ts
src/styles/font.ts

- 로그인 페이지 퍼블리싱 했습니다
> 기록하며 개발하기!
- 말하는 감자.
- 이용약관 text는 디자인 선생님들이 다시 설정해줘야해서 이상해보이는 점 양해 부탁드려요
- `Unexpected console statement.` 이런 린트 에러가 자꾸 뜨는데 어떡하면 좋을까요,, 
- left section의 위치를 조절하고자 냅다 margin-left를 주었는데 이게 반응형에 좋을지 모르겠어서 피드백 부탁드려요
- 뷰에 주어진 대로 width, height값 잡아서 했는데 글자가 자꾸 짤리는 문제들이 발생해서 조금씩 rem 값을 조정해주었는데요, 혹시 다른 이유가 있어서일까요.. 
- LoginBg 이미지 상단에 하얀색 여백이 조금 있어서, 제가 Login Page에서 퍼블리싱할 때 뭔가 잘못한걸까요?
close #327 
https://github.com/user-attachments/assets/17cedc78-788c-4b3c-8861-3ec16f945b79

[FEAT] 로그인 페이지 퍼블리싱

---

src/apis/tasks/deleteTask/query.ts
src/apis/tasks/updateTaskStatus/query.ts
src/components/common/StagingArea/StagingAreaTaskContainer.tsx
src/components/common/v2/control/DropdownButton.tsx
src/components/common/v2/modal/MainSettingModal.tsx
src/components/common/v2/taskBox/Todo.tsx
src/components/targetArea/TargetTaskSection.tsx
src/constants/statuses.ts
src/stories/Common/Button/DropdownButton.stories.ts
src/stories/Common/Button/Todo.stories.tsx
src/stories/Common/dropdown/StatusDropdown.stories.ts
src/stories/modal/MainSettingModal.stories.ts
src/types/tasks/taskType.ts

- task 삭제 api를 연결했습니다.
- task 상태 수정 api를 연결했습니다.
- 서버에서 '진행중'을 '진행 중'으로만 받아서 해당 부분 수정했습니다.
- api 요청에 성공한 상황에 따라서 토스트를 연결해두었씁니다.
- 일단 아무곳이나 모달이 뜨게 해놨슴다. 위치 조정이 필요합니다.
> 기록하며 개발하기!
- 
- `useUpdateTaskStatus`를 통해서 task의 상태를 수정하고 있는데 해당 api를 호출했을 때 쿼리키 무효화로 `useGetTasks`를 불러오긴 하는데 새롭게 불러온 데이터가 화면에 반영이 되지 않고 잇슴다,, 오ㅐ 안되는지 찾아주세요 ㅠㅜㅜ 정답을 알려조
close #337

[FEAT] task 삭제, 상태 수정 api 연결

---

src/components/common/v2/modal/MainSettingModal.tsx

- startTime endTime 부분 옵셔널 체이닝으로 값 없을 경우 대비
- formatTimeWithAmPm 함수에서 time 없는 경우 임시값 리턴되도록 수정
> 기록하며 개발하기!
-
한 피쳐 붙일때 다른부분 건드리는지, 이슈 없는지 확인하고 머지 부탁드립니다 ㅜㅜ
close #366

[FIX] dumping, todo area MainSettingModal 터짐

---

index.html
src/components/common/v2/taskBox/Todo.tsx
src/components/targetArea/TargetArea.tsx
src/components/targetArea/TargetTaskSection.tsx

지원언니가 스타일 onMouse~ 쓰던거 css 로 옮겨서 해결해줘서 기존 올렸던 피알 닫고 필요한 부분만 머지하려고 브랜치 새로 파서 체리픽 해왔어요
- 모달 안열고 바로 상태변경 할수있게 props 연결 수정
- 투두에리아 높이 설정
- shellin 으로 title 변경
변경사항 보기 쉬우라고 지원언니 브랜치로 머지 달앗습니다
close #376

[FIX] #372 변경사항 중 일부 적용

---

index.html
src/components/common/StagingArea/StagingArea.tsx
src/components/common/StagingArea/StagingAreaTaskContainer.tsx
src/components/common/v2/taskBox/Todo.tsx
src/components/targetArea/TargetArea.tsx
src/components/targetArea/TargetTaskSection.tsx

- Todo 컴포 이벤트 중첩때문에 스타일링 간소화했습니다 -> 상태 수정 됨
- react-beautiful-dnd, fullcalendar drag 중복으로 인한 문제 개선했습니다.
> 기록하며 개발하기!
- 안보이게 하면 간단하다
- fullcalendar는 드래그되는 요소에 .fc-event-dragging를 깐다
- ~StagingArea(DumpingArea)에서 Todo컴포 포인터에서 조금 멀리? 잡히는 문제가 있습니다. 저 영역은 뭘까요..~ StagingArea z-index 문제였습니당 해결!
close #350

[REFACTOR] 드래그 모션 개선 + Todo 상태변경 오류 수정

---

src/components/common/Icon.tsx
src/components/common/NavBar.tsx
src/components/common/v2/button/NavbarButton.tsx

- 네브바에 아이콘을 추가하였습니다.
> 기록하며 개발하기!
- stroke 짜증나요
- 앞으로 네브바에 버튼이 어떤 식으로 동작할지 모르겠으나, 현재 버튼과 동일할 것이라는 가정하에 iconbutton 애들 쇽샥해서 재사용 했습니다. 우선은 사이즈나 여러 스타일 타입을 두었지만, 이후 버튼 나오는 거 보고 지워도 될 것 같아여
- svg 아이콘 안에 stroke 색이 자꾸 이상하게 설정되어 있어 진짜 화날 뻔했는데 기존 컴포넌트의 strokecolor 값 때문이었어서, 우선 현재 아이콘과 같은 타입에만 stroke 색상 지정해주었습니다.
- navbar 사이즈가 예전 사이즈로 되어 있는 것 같습니다. 8rem 이어야 하는데 현재는 7.2rem이에요. 근데 이걸 건드리면 다른 컴포넌트 위치에 문제가 생길까봐 우선 건드리지 않았습니다.
close #374 
https://github.com/user-attachments/assets/aaf1c497-a970-4610-a0ac-baade30d36e4

[FEAT] Navbar icon 추가

---

src/components/common/StagingArea/StagingAreaTaskContainer.tsx
src/components/common/v2/taskBox/Todo.tsx
src/components/targetArea/TargetTaskSection.tsx
src/stories/Common/Button/Todo.stories.tsx

- staging, task 영역 나눠서 보정값 넣어서 투두 옆에 뜨게 만듦
close #369

[FIX] 모달위치 수정, staging 모달 인풋 동작하도록 수정

---

.github/workflows/gradle.yaml
src/apis/login/loginAxios.ts

- 구글 로그인 시 인가코드를 넘겨줄 때 redirce url도 함께 넘겨주도록 코드 추가
> 기록하며 개발하기!
-
- 애들아 진짜 진짜 미안하고 사랑해 진짜로 진짜로 미안해,,,,,,, 사랑한다
close #394

[FEAT] 로그인 redirect uri 클라 측에서 전달 

---

src/components/loginPage/GoogleLoginBtn.tsx
src/pages/Login.tsx

- 로그인 뷰 임시로 모바일 대응 가능하도록 추가해두었습니다!
> 기록하며 개발하기!
-
- ex2
close #397

[STYLE] 로그인 뷰 모바일 기기대응

---

src/components/common/v2/TextBox/DumpingAreaBtn.tsx

- 덤핑 인풋 글자수 제한
> 기록하며 개발하기!
-
- 피그마에는 300 자까지라고 되어있기는 한데.. 256부터 서버에서 500 뱉길래 255로 설정해두었습니다
close #424

[CHORE] 할 일 입력 글자 수 제한

---

.github/workflows/test-link-deploy.yml

- 깃헙봇으로 커밋남기려했는데..(큰 의미 없습니다) 설정이 상당히 복잡해서 개인계정으로 재설정했습니다. 
> 기록하며 개발하기!
- 
- 번거롭게 죄송합니다🥹
close #430

[FIX] update GIT_USER config

---

.github/workflows/test-link-deploy.yml

- 환경변수명 변경 (GITHUB_TOKEN 제거) 
- env로 관리 필요없는 내용 제거 (이미 드러나있는 USER, 이메일 등)
- 원활한 테스트를 위해 수동배포 추가
- action 버전업
- PAT 사용을 위해persist-credentials: false 옵션 추가
> 기록하며 개발하기!
- persist-credentials: false 옵션을 추가 안하면 토큰 등록해놨어도 깃허브 자체 토큰인 GITHUB_TOKEN이 자동 사용된다. -> 이거때문에 계속 토큰 오류로 403 오류가 났던거였습니다
- GITHUB_TOKEN 예약어네요.. 수정했습니다
- 다른 레포에서 테스트 해보고 올리는건데, 혹시나 오류 걱정되는 부분 있으면 체크부탁드립니다~
close #433

[FIX] fix test deploy error
