TEAM-DAWM/SHELLIN-CLIENT

.stylelintrc
- stylelint width / height에 rem 단위를 추가했습니다
-  letter-spacing, word-spacing도 em만 설정되어있어서 rem 단위 필요할 것 같으면 확인 부탁드립니다!
close #13
=> [FIX] stylelint rem 단위 추가

.github/workflows/gradle.yaml
- s3 버킷, cloudfront에 자동으로 배포되도록 ci/cd 설정을 완료하였습니다.
- 관련 시크릿키 깃헙에 추가해두었습니다!
-  `AWS_S3_BUCKET_NAME`
- `AWS_S3_ACCESS_KEY_ID`
- `AWS_S3_SECRET_ACCESS_KEY_ID`
- `AWS_CLOUDFRONT_ID`
- **`develop` 브랜치에 push 한 경우에만**(PR 머지) 동작하도록 설정하였습니다.
> 기록하며 개발하기!
- IAM을 사용하지 않고도 s3 배포가 가능하다는 점을 알았다. 근데 보안 측면에서 더 우수하다고 하여 등록하였습니다.
- 엑세스 키, 시크릿 키는 **노출이 되면 새로 발급받아야함 & 모르는 사이 큰 금액 청구될 수 있음** 이니 주의 부탁드립니다! (노션 공유계정 공간에 올려두겠습니다.)
- 깃헙에 올라간 파일에는 주석 제거해두었습니다! 코드 관련한 부분은 밑에 주석부분 참고해주세요!
```yaml
name: Front Deployment
on:
push:
branches:
- develop
jobs:
build-and-deploy:
name: Build and Deploy to AWS S3
runs-on: ubuntu-latest
steps:
- name: Checkout repository
uses: actions/checkout@v3
- name: Setup Node.js
uses: actions/setup-node@v2
with:
node-version: '20' 
cache: 'yarn' 
- …
```
=> [BUILD] CI/CD 구성

.github/workflows/gradle.yaml, src/components/common/textbox/TextInputStaging.tsx, src/pages/Calendar.tsx, src/pages/DashBoard.tsx, src/pages/Login.tsx, src/pages/Setting.tsx, src/pages/Today.tsx
- develop에 PR시 **액션이 실행되지 않고 스킵되는 문제**를 수정하였습니다. 
if문이 develop 브랜치가 PR을 올릴 때 액션이 돌아가도록 설정되어있어서ㅜㅜ, 해당 부분 삭제하였습니다!
- 테스트 설정을 아직 따로 하지 않아서, `yarn test` 부분도 삭제하였습니다! 추후에 테스트 설정 시 추가하면 될 것 같아요
> 기록하며 개발하기!
- if에 develop에 pr 시 돌아가도록 하였는데, 제대로 적용되지 않았습니다. 
**`github.ref`는 PR의 헤드 브랜치가 되며, `github.base_ref`가 타겟 브랜치(이 경우엔 develop)라는 구분**을 알았다!
https://velog.io/@excellent/Github-Action-Context
https://docs.github.com/ko/actions
(처음 논의한 의도대로 on 으로 설정한 모든 경우에 ci도 돌아가도록 if 문을 삭제하였습니다)
- 의도대로 설정되었는지 확인 부탁드립니다 ㅎㅎㅜㅜ
close #33
=> [FIX] develop에 PR 시 action 스킵되는 오류 수정

src/styles/theme.ts
- theme에 button에 사용되는 색상값을 추가하였습니다.
- button 내 light / default / hover / pressed 중에 선택하신 다음, icon 색상을 설정할지, 백그라운드 색을 설정할 지에 따라 icon과 bg를 선택하셔서 색상을 추가하시면 됩니다!
- bg가 아닌 아이콘과 텍스트 컬러는 모두 icon에서 선택해서 사용하시면 됩니다.
- clicked는 pressed에서, disabled는 light에서 선택하셔서 사용하시면 됩니다!
`${({ theme }) => theme.button.light/default/hover/pressed.icon/bg}`
close #44
=> [FEAT] theme button 색상값 적용

src/components/common/BtnDate/BtnDate.tsx, src/pages/Today.tsx
- 마감기한 공통 컴포넌트에서, 지연 상태일때의 스타일이 추가되어서 props에 `isDelayed`를 이용해 구현하였습니다!
> 기록하며 개발하기!
- `isDelayed`일때는(: 지연상태) hover / pressed / clicked가 발생하면 안된다. 이 경우를 하나하나 상태 엮어서 스타일링 해야하나 했는데, **`pointer-events: none;`** 라는 것을 이용하면 다음 이벤트들이 막아진다는 것을 알았다!
- size가 small일때만 사용되는 스타일링이지만, size 역시 props로 넘겨받기에 따로 제한을 걸어두지는 않았습니다! 제한을 거는 것이 좋을 지 코멘트 부탁드려요! 
close #59 
https://github.com/TEAM-DAWM/NUTSHELL-FE/assets/128016888/b65443d6-96e0-42c8-96f2-6448e6926f03
=> [FEAT] 마감기한 공통컴포넌트 - 지연 상태일때의 스타일 추가

src/components/common/BtnDate/BtnDate.tsx
- Calandar, Clock, Line Icon의 stroke 색상이 default 상태에서 검은색으로 보이는 부분을 수정하였습니다.
- 여러 곳에서 사용되는 버튼이라 빠른 머지를 위해 PR 생성하여 색상 변경 하였습니다! 
close #66
=> [FIX] Calandar, Clock, Line Icon stroke 색상 수정

src/components/common/ScrollGradient.tsx, src/pages/Today.tsx
- 스크롤 하단에 gradient를 통해 구분하는 부분이 공통으로 적용되는 부분이라, `common/` 에 컴포넌트 생성하였습니다!
> 기록하며 개발하기!
- linear-gradient를 설정해도 안보인다면 배경색을 깔아보자..! 그림자도 흰색, 배경도 흰색이라 적용 안되는 줄 알았다.
- 스크롤 적용되는 부분의 밑에 적용하여 사용해주시면 됩니다! width는 자동으로 맞춰집니다!
close #68 
연두색 부분입니다!
=> [FEAT] 스크롤 하단(gradient 적용) 공통 컴포넌트 생성

src/components/common/ScrollGradient.tsx
- ScrollGradient 컴포넌트가 사용되는 모든 부분에서 하단에 위치하여서, 해당 컴포넌트 단에서 위치를 하단으로 고정하였습니다!
> 기록하며 개발하기!
- `position: sticky` 라는 속성에 대해 알았다. 
'요소는 처음에 문서의 정상적인 레이아웃 흐름에 따라 배치지만, 사용자가 스크롤할 때 요소가 **지정된 위치에 도달하면 요소는 화면에 고정**됩니다. 이 고정 위치는 상단, 하단, 왼쪽, 오른쪽 등의 방향을 기준으로 지정할 수 있습니다.'
- 해당 부분 업데이트 하여 사용해주시면 됩니다 감사합니다!
close #70
=> [FIX] ScrollGradient 컴포넌트 위치 고정

src/components/common/BtnTask/BtnTask.tsx, src/components/common/StagingArea/StagingArea.tsx, src/components/common/StagingArea/StagingAreaSetting.tsx, src/components/common/button/EnterBtn.tsx, src/components/common/button/textBtn/TextBtn.tsx, src/components/common/button/textBtn/textBtnStyle.ts, src/components/common/textbox/TextInputStaging.tsx, src/pages/Today.tsx, src/types/textBtnType.ts
- StagingArea(: 쏟아내기) 부분을 퍼블리싱했습니다!
- 구현 과정에서 **기존 컴포넌트들의 변경 사항**이 있습니다.
- `TextBtn.tsx` 버튼에 클릭이벤트를 추가하여 **전체<->취소** 버튼 등의 커스텀 가능하도록 하였습니다!
- `TextInputStaging.tsx` 버튼의 임시버튼을 생성 완료된 버튼컴포넌트를 이용해 변경하였습니다!
- **수정 필요한 사항: `ArrangeBtn`의 hover일때와 기본 상태일 때의 스타일링 변경이 필요합니다.**
- `TextBtn.tsx` 버튼에 클릭이벤트를 추가하여 **전체<->취소** 버튼 변경 로직이 적절한 지 검토 부탁드려요!
close #62 
https://github.com/TEAM-DAWM/NUTSHELL-FE/assets/128016888/e4d6629c-2069-4f1b-83b3-16309a28dc09
=> [FEAT] StagingArea 퍼블리싱

src/components/DashboardPage/TaskSummary.tsx, src/constants/tasksPeriod.ts, src/pages/DashBoard.tsx
- 대시보드 뷰 하단 task 요약 박스 컴포넌트를 구현했습니다.
- 고양이 이미지 부분은 디자인에서 3D 이미지를 넘겨주실 예정이라 하여 영역만 잡았습니다. 참고해주세요!
> 기록하며 개발하기!
- _api 연동해야 하는 부분을 상수 데이터로 가져오는 법은 알고 있었지만, 테스크 요약 컴포넌트의 경우 지연된 일인지, 완료된 일인지, 진행 중인 일인지에 따라 보여줘야 하는 api 데이터가 달라 고민이 되었습니다. 먼저 상수 데이터에 api 데이터를 가져온 뒤, let 으로 summaryNumber가 숫자임을 선언해준 뒤, 각각의 props 타입에 따라 api 데이터를 가져와주었습니다. 하하 별거 아니지만 뿌듯해요 ~~~ 잉 ㅋ 🏄_ > **갈아엎었습니다.**
- 하나의 컴포넌트 안에서 let으로 props 타입에 따라 api 데이터를 가져와줄 경우, 호이스팅이 3*3 9번이나 발생한다는 문제가 있다는 피드백을 받았습니다. 따라서 상위 페이지에서 api 데이터를 포함한 값을 배열로 선언해준 뒤, 상위 페이지에서 map 함수를 돌리고, 하위 컴포넌트에 props를 인자로 내려주었습니다. map 함수를 매번 어려워했는데 이번 기회에 잘 사용한 것 같아서 기분이 좋습니다. 그리고 또 알게된 사실, 상위에서 props를 내려주더라도 하위에서 역시 타입 선언을 해줘야하는 군요,, 당연하지만 저는 몰랐습니다. 더 공부하겠습니다아아!
- _말씀드린 대로 api 연동하는 부분을 상수 데이터 + 숫자 타입 함수로 가져와주었는데, 혹시 이 부분에 대해서 더 좋은 …
=> [FEAT] 대시보드 뷰 task 요약 컴포넌트 퍼블리싱 (하단 컴포넌트)

src/components/DashboardPage/DashboardTask.tsx, src/constants/dashboardTask.ts, src/constants/tasksToday.ts, src/pages/DashBoard.tsx
- 대시보드 뷰의 task 컴포넌트를 구현했습니다.
- 다가오는 할 일 / 지연된 할 일 / 진행중인 할 일 텍스트는 text를 prop으로 받아 작성하시면 됩니다. 혹시라도 더 좋은 방법이 있다면 알려주세요!
- Btntask 컴포넌트가 박스 사이즈를 넘어가면 무한 스크롤이 생성되도록 구현하였습니다.
> 기록하며 개발하기!
- 그라디언트 속성을 어떻게 줄 수 있을지 감이 잘 안왔는데 지원이가 태그를 넣기만 하면 바로 적용되도록 공통 컴포넌트를 잘 빼주어서 편리하게 사용할 수 있었습니다. 기억 속 잊혀졌던 z-index와 sticky 속성, 그리고 bottom 을 0으로 주어 컴포넌트의 하단에 그라디언트를 잘 줄 수 있었습니다.
- 스크롤바를 처음 넣어봐서 감도 안오고 잔뜩 겁먹었었는데 생각보다 별게 아니었습니다. 심지어 커스텀할 일도 없었음... overflow를 scroll로 주면 되는거였습니다.. 레전드 간단. . 슛~! 슛!!🚀
- task 개수는 api를 연동해야 해서 우선은 하드코딩으로 때려박았습니다. (사실 다가오는 일 / 지연 / 진행 중 별로 상수 데이터를 어떻게 가져올 수 있을지 감이 안와서 하드코딩한 부분도 있는데 뷰 구현 담당자가 상수 데이터로 박아놓는게 좋은 것 같다면 관련하여 피드백 함께 부탁드리면 반영해보도록 하겠습니다!)
close #64
`구현한 컴포넌트(파란 박스 영역 안)`
`구현 영상`
https://github.com/TEAM-DAWM/NUTSHELL-FE/assets/151596186/d188fade-74ca …
=> [FEAT] 대시보드 뷰 task 컴포넌트 퍼블리싱

src/components/common/button/SortBtn.tsx, src/components/common/modal/ModalArrange/ModalArrange.tsx, src/constants/sortType.ts, src/pages/Today.tsx
- Today 페이지의 Staging Area에서의 정렬 기능을 수행할 Arrange Modal을 퍼블리싱 하였습니다.
- `activeSorByDateAdded`(최신 등록순, 오래된 등록순) / `activeSorByDeadLine`(가까운 마감기한순, 먼 마감기한순) 로 크게 구분 가능합니다. 각 세트별로 정렬 선택 가능한 부분이라 상태를 2개로 나눴습니다!
- Staging Area(:쏟아내기)에서 `SortBtn` 클릭 시 사용될 모달입니다!
- **`activeSorByDateAdded`(최신 등록순, 오래된 등록순)** / **`activeSorByDeadLine`(가까운 마감기한순, 먼 마감기한순)** 은 각 세트별로 정렬 선택 가능한 부분이라 상태를 2개로 나눴습니다! 
close #86
=> [FEAT] Arrange Modal 생성

src/components/common/datePicker/CorrectionCustomHeader.tsx, src/components/common/datePicker/CustomHeader.tsx, src/components/common/datePicker/DateCorrectionModal.tsx, src/components/common/datePicker/DatePickerStyle.tsx, src/components/common/textbox/TextboxInput.tsx, src/pages/DashBoard.tsx
날짜, 시간 수정 데이트피커 모달 제작했습니다
기존 데이트피커에서 props 로 분기처리하기에는 너무 복잡해질 것 같아 수정 모달은 새로운 컴포넌트를 만들었습니다  
`isDateOnly` boolean 타입의 값을 통해서 시간 설정하는 인풋 표시 여부를 결정합니다  
시간 설정하는 부분 인풋창 시간 포맷팅 안된 상태이고
기존 선택된 날짜인 prevDate 스타일 지정 안된 상태입니다! 이후 추가 예정입니다
close #78
=> [FEAT] 날짜, 시간 수정 데이트피커 모달 제작

src/components/common/datePicker/DateCorrectionModal.tsx, src/components/common/textbox/TextboxInput.tsx, src/utils/checkTimeFormat.ts, src/utils/dotFormatTime.ts
-  숫자 이외 입력 막기
-  자동 포맷팅 구현
-  데이트피커 모달에 연결하기
> 기록하며 개발하기!
다시 보니까 모달에서 시간을 눌러서 설정하는 방식은 없어서 `onTimeChange`를 제거하고 텍스트 인풋 -> 시간 설정 방식만 유효하게 했습니다  
`time, setTime` 상태 만들었는데 지금 사용하지는 않아서 주석처리 해뒀습니다 ! 나중에 모달 연결할 때나 기능 연결할 때 풀어써 쓰면 될 것 같습니다.  
00:00 ~ 23:59 내의 유효한 시간인지 확인하고 유효하면 끝까지 입력되도록, 유효하지 않으면 알러트 뜨고 입력 초기화되도록 설정해두었습니다. 
close #92
=> [FEAT] 시간 포맷팅 추가

src/components/common/textbox/TextboxInput.tsx, src/utils/checkDateFormat.ts
- 날짜 인풋 유효성 검사 유틸 함수를 만들었습니다
- 그리고 `TextboxInput`에 추가했습니다.
> 기록하며 개발하기!
day <= 31 조건을 명시적으로 추가하지 않아도 `new Date(year, month, 0).getDate()`가 해당 월의 최대 일수를 반환해서 이 조건이 없어도 32일이나 31일이 없는 달의 31일이 잘 걸러짐!  
그래도 명시적으로 조건을 표시해두긴 하였습니다.
이상한 값 넣었을 때 잘 막아지는지 확인해주시면 감사하겠습니당
close #97
=> [FEAT] 날짜 인풋 유효성 검사

src/components/common/BtnDate/BtnDate.tsx
- `isDelayed` 오류 수정하였습니다!
- styled-coponent에 props 전달하는 과정에서 리엑트가 워닝을 내뿜어서 수정했습니다.
> 기록하며 개발하기!
- 기존 사용한 방식(`XIcon`에 사용)대로 하면 오류났던 이유가 svg 컴포넌트를 직접 건들기때문에 해당 DOM으로 한번 더 전달되기 때문이라고 합니다. 
`shouldForwardProp`를 사용하면 props가 DOM 요소에 전달되지 않고 컴포넌트 내에서만 사용된다고 합니다! 
- 계속 거슬렸던 `isDelayed`오류 수정했습니다.. 수정 사항 체크해주세요!
close #98
=> [FIX] styled-coponent에 props 전달 오류 수정

src/components/common/BtnDate/BtnDate.tsx, src/components/common/BtnTask/BtnTask.tsx, src/pages/Today.tsx
- BtnDate의 사이즈에 따른 height가 잘못 설정되어있어 해당 부분 수정하였습니다.
- 수정하는 김에 size props의 타입도 string에서 SizeType으로 변경하였습니다!
> 기록하며 개발하기!
- 여러번 전달(연동?)되는 부분은 통일된 타입을 사용하자!
- props 타입과 높이를 수정하였습니다
close #107
=> [FIX] BtnType props 타입 및 height 수정

src/components/calendarPage/CategoryBox.tsx, src/components/common/fullCalendar/FullCalendarStyle.ts, src/pages/Calendar.tsx, src/pages/MainLayout.tsx
- 1366px x 768px 에 맞춰서 캘린더 뷰 퍼블리싱을 진행했습니다.
- 빨간색 선이 해상도 크기이고 그 크기에 맞춰서 배치 조정을 했습니다.
> 기록하며 개발하기!
-
- 카테고리의 경우 위에 있는 미니 캘린더가 길어지면 줄어드는 크기를 계산해서 min, max height를 지정했는데 이것보다 좋은 방법이 있다면 말씀해주세용.. height : 100%로하면 꽉안차서 이렇게 진행을 했습니다.
close #103
=> [FEAT] 캘린더 뷰 퍼블리싱

src/components/common/BtnDate/BtnStagingDate.tsx, src/components/common/BtnTask/BtnTask.tsx, src/components/common/StagingArea/StagingArea.tsx, src/components/common/StagingArea/StagingAreaSetting.tsx, src/components/common/StagingArea/StagingAreaTaskContainer.tsx, src/components/common/datePicker/DateCorrectionModal.tsx, src/components/common/fullCalendar/FullCalendarStyle.ts, src/components/common/modal/Modal.tsx, src/components/common/modal/ModalArrange/ModalArrange.tsx, src/components/common/textbox/TextInputStaging.tsx, src/components/targetArea/TargetArea.tsx, src/components/targetArea/TargetTaskSection.tsx, src/pages/MainLayout.tsx, src/pages/Setting.tsx, src/pages/Today.tsx
- Today 페이지 퍼블리싱입니다. PR이 너무 길어질 듯 하여 StagingArea 모달 연결까지만 진행 후 나눠서 PR 올리겠습니다!
- 생성 완료된 공통 컴포넌트를 통해 Today 뷰 퍼블리싱을 마쳤습니다.
- StagingArea의 모달을 3개 연결하였습니다. 
- 정렬 모달
- Task 추가 모달
- Task 할당 모달
- 배경에 background 넣고 모달 제외부분 클릭 시 모달 닫히도록 구현했습니다! ㅜㅜ저한텐 너무 어려웠습니다 😖😫🥺
- **스크롤 문제 해결** 🥹
웹사이트 기본 제공 스크롤 스타일이 사람마다 다른 점을 고려하여 스크롤 스타일을 추가하였습니다.
스타일을 추가하니 그만큼의 자리를 차지하여 뷰가 옆으로 밀리는 현상이 발생하여 해당 부분 수정하였습니다.
```css
const TaskContainer = styled.div`
display: flex;
flex-direction: column;
gap: 1rem;
width: 100%;
height: 64rem;
overflow: hidden; /* 가로스크롤 숨김 */
overflow-y: scroll; /* 스크롤 없을때도 자리 차지하도록 */
/* 스크롤 스타일 커스텀 */
::-webkit-scrollbar {
width: 0.6rem;
}
::-webkit-scrollbar-thumb {
background-color: ${({ theme }) => theme.palette.Grey.Grey6};
border-radius: 3px;
}
`;
```
> 기록하며 개발하기!
- 성희 피알 보고 버튼에 `position: …
=> [FEAT] Today 페이지 퍼블리싱 + StagingArea 모달 연결

src/components/common/button/settingBtn/SettingDeleteBtn.tsx, src/components/common/modal/ModalDeleteBtn.tsx, src/components/common/modal/ModalDeleteDetail.tsx, src/components/common/textbox/TextInputDesc.tsx
Today 페이지의 Task 할당 모달 중 수정사항을 해결하였습니다.
- **`ModalDeleteDetail` 모달이 잘리는 문제**
- `position: absolute;` -> `position: fixed;` 로 변경 후 ref 통해 삭제버튼의 위치 받아와서 위치 조정
- BackDrop 적용하여 모달 제외 배경 클릭 시 모달 닫히도록 구현
- **`Modal`의 설명 추가 input 창에서, focus 시 border 색변화 제거** (디자인 요구사항) 
> 기록하며 개발하기!
- 이제 모달 위치조정 잘합니닷 ㅋㅋ
- 모달 위치가 요구사항에 맞게 조정되어있는지 확인부탁드립니다!
close #113
=> [FIX] Task 할당 모달 스타일 수정

src/components/common/datePicker/CorrectionCustomHeader.tsx, src/components/common/datePicker/CustomHeader.tsx, src/components/common/datePicker/DateCorrectionModal.tsx, src/components/common/datePicker/DatePickerCustom.tsx, src/components/common/textbox/TextboxInput.tsx, src/utils/formatDatetoString.ts, src/utils/refStatus.ts
- 시간, 날짜 형식 체크 후 실패시 alert 처리 했었는데, 이를 인풋창 배경색과 테두리 색상 피드백으로 변경했습니다
> 기록하며 개발하기!
- 이해하기 쉬운 코드와 중복이 적어 간결하게 적힌 코드 사이에서 고민이 되었습니다
- 간결하게 적은 코드의 경우 적은 양의 코드로 분기처리를 해서 로직을 수행하는 대신 직관적으로 이해하기 힘들었고, 모든 케이스를 명시적으로 작성한 경우 가독성과 직관성은 가져가지만 중복 코드를 많이 작성해야 했습니다
- 현재는 중복 로직을 줄이고 조건에 따라 분기했습니다
또 focus 는 ref 에만 되는 거 아닌가? 하는 우려가 있었는데 생각해보니 그냥 보더라인 색상 바꾸게 되어 있어서 ref 위치만 바꿔주었습니다. 별개로 div에 focus 주려면 tabindex 속성을 조정하면 된다고 하네요 ..
- 코드가 이해가 잘 되는지, 인풋 엣지케이스에도 잘 동작하는지 확인해주시면 감사하겠습니당
close #105
=> [FEAT] TextBoxInput 날짜, 시간 체크 실패시 피드백

src/components/common/BtnDate/BtnDate.tsx, src/components/common/BtnTask/BtnTask.tsx, src/components/common/BtnTask/IconHoverContainer.tsx, src/components/common/button/OkayCancelBtn.tsx, src/components/common/modal/Modal.tsx
- doubleclick 시 모달 띄우기
기존에는 클릭으로 보더 스타일, 모달 전부 컨트롤했었는데 더블클릭으로 모달 뜨도록 제작하고 클릭으로는 스타일만 컨트롤하도록 변경했습니다.  
- `BtnTask` 에서 `IconHoverContainer` 분리
`BtnTask` 컴포넌트 코드가 너무 길어져서 호버하면 아이콘이 뜨는 부분인 `IconHoverContainer`를 분리했습니다  
- `XIcon` styled component props 단순화  
- 태스크 목록에서 `BtnDate`가 사용될 경우 short size 로 사용되는데, 이 경우 clicked, pressed, hover를 막았습니다  
혹시 `BtnDate`가 short size로 사용되는 경우가 태스크 목록 이외에도 있다면 알려주세요!
close #117
=> [FEAT] TaskBtn 더블클릭, 클릭 인터랙션 분리

src/components/common/fullCalendar/FullCalendarBox.tsx, src/components/common/fullCalendar/FullCalendarStyle.ts, src/styles/GlobalStyle.tsx
- 서버로부터 받아오는 이벤트를 class로 구분하여 taks와 schedule을 구분할 수 있도록 하였습니다.
- 각 이벤트의 호버 색상도 추가하였습니다.
> 기록하며 개발하기!
-  `[style*='user-select: none']`이런식으로 드래그할 때의 스타일을 적용할 수 있음을 알았습니다.
close #110
=> [FEAT] fullCalendar task와 schedule 구분

src/components/common/BtnDate/BtnDate.tsx, src/components/common/BtnTask/BtnTask.tsx, src/components/common/StagingArea/StagingAreaSetting.tsx, src/components/common/datePicker/DateCorrectionModal.tsx, src/components/common/modal/Modal.tsx, src/components/common/modal/ModalBackdrop.tsx, src/components/common/modal/ModalDeleteDetail.tsx, src/components/common/textbox/TextInputDesc.tsx, src/components/common/textbox/TextInputStaging.tsx, src/components/targetArea/TargetControlSection.tsx, src/constants/modalLocation.ts, src/types/arrangeBtnType.ts
Today 페이지의 모달 중 `DateCorrectionModal`을 다음 3군데에서 연결하였습니다.
(주황색 테두리는 서비스 전체화면 크기를 잡아둔 부분입니다!)
- 연동이 필요한 값은 아직 연결해두지 않았습니다! 우선적으로 모달이 열리는 부분까지만 구현해두었습니다.
- BackDrop은 모든 모달 전체 화면에 설정해두었습니다!
<br>
**추가 수정사항**
- `arrangeBtnType`에서 onClick 타입 확장성 위해 void로 변경하였습니다.
- `BtnDate`(: 마감기한 & 마감시간 나타나는 모달)에서 size 관련 수정사항 적용 중, x 버튼이 필터링 안되어있어 해당 부분 추가 수정하였습니다!
> 기록하며 개발하기!
- `position: absolute;` 설정 시 화면이 꽉 안찬다면 top, left, bottom, right 속성을 전부 0으로 줘보자!
- 모달이 적절한 위치에 띄워지는 지 + 혹시 플로우에 문제가 있을 지 확인부탁드립니다!! 
close #112
=> [FEAT] Today 뷰 모달 연결

src/components/calendarPage/miniCalendar/MiniCalendar.tsx, src/components/common/fullCalendar/FullCalendarBox.tsx, src/pages/Calendar.tsx
- 미니 캘린더의 날짜를 이동하면 풀캘린더의 날짜도 이동하는 기능을 구현하였습니다. 
-  ref로 FullCalendar 컴포넌트를 참조하게 해서 `getApi()` 메서드를 호출하고 `FullCalendar`의 API 인스턴스를 가져왔습니다.
> 기록하며 개발하기!
-`calendarApi`의 `gotoDate` 메서드는 캘린더를 `selectDate` 날짜로 이동시킵니다.
- useRef를 통해 생성된 객체는 current라는 프로퍼티를 가지게 됩니다. 그리고 이 current를 통해 실제 DOM 노드에 접근할 수 있습니다.
- ref를 사용하여 컴포넌트를 재생성하지 않고 날짜를 동적으로 변경할 수 있어 ref를 사용하여 날짜를 변경하는 방법을 선택했습니다.
close #110
=> [FEAT] 캘린더 날짜 맞추기

src/components/common/BtnTaskContainer.tsx, src/components/common/StagingArea/StagingAreaTaskContainer.tsx, src/components/targetArea/TargetTaskSection.tsx
기본 스크롤바에 visibility hidden 속성을 주고 
```css
&:hover::-webkit-scrollbar-thumb {
visibility: visible;
}
```
해서 호버시에만 스크롤바가 보이도록 했습니다.  
그리고 TaskArea 와 StagingArea 에서 BtnTask 를 감싸는 컴포넌트가 동일한 기능 수행, 동일한 스타일링을 가지고 있는 것 같아 분리한 후 재사용할 수 있도록 제작했습니다.
컴포넌트 통일로 인해 다른 컴포넌트와의 상호작용에 문제가 생기는 부분이 있다면 제보 바랍니다 ...
close #126
=> [FEAT] 스크롤할 때만 스크롤바 보이도록 설정

src/components/common/fullCalendar/FullCalendarBox.tsx, src/constants/modalLocation.ts
- FullCalendar의 events에 클릭이벤트 추가(모달 연결)을 하였습니다!
> 기록하며 개발하기!
- fullcalendar 라이브러리에서는 각 이벤트를 클릭하는 `eventClick` 속성을 지원한다.
이때의 props 타입은 `EventClickArg` 라고 한다.
```typescript
const handleEventClick = (info: EventClickArg) => {};
```
해당 부분에서 `info.event.title` 과 같은 방식으로 클릭된 이벤트의 정보를 불러올 수 있다.
- 모달에 이벤트가 덮히는 문제로, 모달 위치를 조정하였습니다. 이상하다면 수정하겠습니다!
close #123
=> [FEAT] FullCalendar events에 모달 연결

src/components/DashboardPage/DateArea.tsx, src/components/DashboardPage/DatePickerPlaceholder.tsx, src/components/common/datePicker/DatePickerCustom.tsx, src/constants/getPastDate.ts, src/pages/Calendar.tsx, src/utils/formatDatetoStringKor.ts
- datePicker 상위 컴포넌트에서 관리하는 useState 값을 date picker 에도 인자로 내려주었습니다!
- 모달에서 날짜를 선택하면 버튼에 반영이 됩니당
- 데이트 피커에서 어떤 날짜값을 입력하든, 1주 전, 1달 전 버튼을 누르면 현재 날짜 & 현재 날짜 기준 1주/1달 전 날짜가 나오도록 설정했습니다. (사이드 이펙트 오져버려서 애좀 먹었어요..)
- 데이트피커에서 실시간으로 선택하는 값에 따라 placeholder에 Null 값이 들어가지 않도록 했습니다! (빈 공백이 placeholder에 렌더링되지 않도록)
> 기록하며 개발하기!
- setter 함수를 직접 사용하는 걸 지양하는게 좋다고 해서 handleStart/EndDate로 한번 선언해준 뒤 사용해주었습니다!
- 타입 에러를 잡는게 조금 어려웠습니다.. 자스의 Date 객체를 자주 활용하고 깊이 알아갈 수 있는 기회였습니다,, 
- 초기값 설정, 그리고 useEffect와 더 친해지는 계기였습니다. 여기저기 초기값이 다르고 렌더링되는 시점이 달라 개짜증나는 사이드 이펙트와 싸워야했어요..
- 하나 수정할 때마다 다른 에러 발생하고, 에러가 팡팡팡 미친듯이 나고 사이드 이펙트 지려버리고 타입 에러도 오져버려서 type 선언에서 date|null을 남발하였습니다.  혹시 좋지 않은 방식이라면 피드백 주세요!! 
- 아래와 같은 에러가 뜨는데, 해당 로직은 placeholder에서 가장 처음에 {현재 날짜} 와 {2주 전 날짜}를 보여주는 기능입니다. 때문에 초기값만 …
=> [FEAT] datepicker 값 버튼에 연결

src/components/DashboardPage/DashboardTask.tsx, src/components/common/BtnTask/BtnTask.tsx, src/components/common/StagingArea/StagingArea.tsx, src/components/common/StagingArea/StagingAreaTaskContainer.tsx, src/components/common/fullCalendar/FullCalendarBox.tsx, src/components/targetArea/TargetArea.tsx, src/components/targetArea/TargetTaskSection.tsx, src/pages/Calendar.tsx, src/pages/DashBoard.tsx, src/pages/Today.tsx
- 태스크 선택을 하나만 할 수 있도록 state를 만들어 관리합니다. 기존 border 색상을 관리하던 isClicked 상태를 삭제하고 해당 state로 묶었습니다.
- Today 에서 selectedTarget state를 TaskType로 받습니다.
- task 담겨있는 컴포넌트들과 캘린더를 위 state로 연결해 드래그하면 해당되는 이벤트가 추가됩니다.
- 이미 같은 id의 이벤트가 있는 경우 이벤트를 지우고 새로 생성합니다
- 대시보드에서도 하나만 선택할 수 있도록 설정했습니다. 이후 변동시 수정하겠습니다
> 기록하며 개발하기!
- full calendar api를 이용해 이벤트를 생성하는 방법을 알게 되었습니다
```tsx
if (calendarRef.current && (selectedTarget?.id === 0 || selectedTarget)) {
```
0이 false 한 값으로 처리되어 위와 같이 처리했는데, 0을 제외한 falsy 값을 걸러낼 수 있는 더 좋은 방법이 있는지 궁금합니다.
close #130
=> [FEAT] BtnTask 선택 후 캘린더 긁기

.gitignore, package.json, src/apis/instance.ts, src/apis/login/loginAxios.ts, src/apis/login/loginInterface.ts, src/apis/messages.ts, src/main.tsx, src/pages/Login.tsx, yarn.lock
- react-oauth/google 라이브러리를 이용해서 구글 로그인을 구현하였습니다.
- 토큰이 필요없는 api요청을 보내는 axios인스턴스와 토큰이 필요한 api요청을 보내는 axios인스턴스를 각각 만들고, interceptors를 이용해서 Refresh token으로 다시 access Token을 요청할 수 있게 하였습니다. 
- ex3
> 기록하며 개발하기!
-  useGoogleLogin를 사용하면 라이브러리 자체에서 알아서 리다이렉트가 진행되는데 해당 url은 localhost:5174라고 합니다.
- axios.post 메소드를 호출할 때, 세 번째 인수로 params를 전달하기 위해 두 번째 인수로 null을 넣어야 합니다.
- api 폴더구조를 고민하다가 현재처럼 하였는데 더 좋은 대안이 있다면 말씀해주세요!
- interceptors 구조도 좋지 않은 것 같아서 코드 리뷰 바랍니다. 
- 카카오톡에 공유한 env는 해당 pr이 머지하고 추가해주세요! 안그러면 커밋하다가 env가 올라갈 위험이 있습니당
close #131
=> [FEAT] 구글 소셜 로그인 api 연결

src/components/common/BtnDate/BtnDate.tsx, src/components/common/BtnTask/BtnTask.tsx, src/components/common/BtnTaskContainer.tsx, src/components/common/StagingArea/StagingAreaTaskContainer.tsx, src/components/common/datePicker/CorrectionCustomHeader.tsx, src/components/common/datePicker/CustomHeader.tsx, src/components/common/datePicker/DateCorrectionModal.tsx, src/components/common/fullCalendar/FullCalendarBox.tsx, src/components/common/modal/Modal.tsx, src/components/common/modal/ModalDeleteDetail.tsx, src/components/common/modal/TextInputBox.tsx, src/components/common/textbox/TextInputDesc.tsx, src/components/common/textbox/TextInputStaging.tsx, src/components/common/textbox/TextInputTitle.tsx, src/components/common/textbox/TextboxInput.tsx, src/components/targetArea/TargetControlSection.tsx, src/components/targetArea/TargetTaskSection.tsx, src/stories/Button/OkayCancelBtn.stories.ts, src/types/tasks/taskType.ts
- 모달과 데이트피커 날짜, 시간 정보를 연결했습니다
- `Modal` 컴포넌트에 `taskId`를 props 로 받게 해주어서 상세정보 요청을 `taskId`로 하시면 됩니다! 임시로 5로 박아둔 상태고 나중에 값 연결할 때 데이터 형식 잘 확인하고 연결하면 될 것 같아요  
- 타입 관리를 용이하게 하기 위해서 기존에 date, time이 `Date|'마감 시간'` 와 같은 구조로 되어있던 것을 `Date|null` 로 변경하고, null 일 경우에 마감시간 마감기한 등 스트링을 주고 스타일링도 변경하는 방식으로 변경했습니다.  
- `BtnTask` 내의 정보는 리스트 불러오는 api 에서 가져오고, 모달에 있는 정보는 `taskId`를 이용해서 상세정보를 불러오기 때문에 모달에만 시간 날짜를 임시저장하고 정보 등록하는 api 호출에 사용할 수 있도록 state를 사용했습니다.  
- 더 나은 구조가 있다면 리뷰로 달아주세요!
close #142
=> [FEAT] 모달에 정보 연결하기

src/components/SettingPage/AccountArea.tsx, src/components/SettingPage/AccountDeleteBtn.tsx, src/components/common/button/DeleteCancelBtn.tsx, src/components/common/modal/ModalDeleteDetail.tsx, src/pages/Setting.tsx
- 세팅 페이지에서 계정 삭제 버튼을 누를 때 취소, 삭제 버튼이 나타나도록 했습니다.
- 기존에 만들어두었던 ModalDeleteDetail 컴포넌트를 사용하였습니다.
- 기존에는 버튼에 onClick이 없어서 props에 onClick을 추가하고 취소 버튼에는 close 함수를 연결하였습니다. 
> 기록하며 개발하기!
- 
- 확인해보시고 추가 수정할 부분 말씀해주세요!
close #153
=> [FEAT] 세팅 페이지 취소, 삭제 버튼 추가

src/components/DashboardPage/DashboardTask.tsx, src/components/common/BtnTask/BtnTask.tsx, src/components/common/BtnTask/IconHoverContainer.tsx, src/components/common/StagingArea/StagingAreaTaskContainer.tsx, src/components/targetArea/TargetTaskSection.tsx, src/pages/Today.tsx
- Task버튼(`BtnTask.tsx`) 스타일 및 hover 시 나타나는 Icon 수정사항 반영
- 수정사항 반영을 위해, 버튼을 구분하는 props 내용을 변경하였습니다. 또한 보다 높은 가독성을 위해 내부 타입명도 변경하였습니다.
```typescript
interface BtnTaskProps extends TaskType {
iconType: 'stagingOrDelayed' | 'active';
btnStatus?: '진행중' | '미완료' | '완료' | '오늘로추가';
}
```
위의 내용 중, btnStatus와 status가 하나 빼고 동일하지만 같은 값을 사용하는 것이 오히려 혼란을 일으킬 듯 하여 따로 만들었습니다. 더 나은 방법이 있다면 추천 부탁드립니다!
<br>
- 사용 시에는 밑에 이미지 참고해주세요!
close #159 
차례대로 적용한 코드
=> [FIX] Task버튼 스타일 및 hover Icon 수정사항 반영

src/apis/tasks/getTask/GetTasksType.ts, src/components/targetArea/TargetArea.tsx, src/components/targetArea/TargetTaskSection.tsx, src/utils/formatDatetoLocalDate.ts
- TargetArea 쪽 더미데이터 빼고 api 연결했습니다
- date 전달 위해서 유틸에 LocalDate 포맷으로 변경하는 함수 하나 더 만들었습니다.
close #173
=> [FEAT] task get api TargetArea 연동

src/apis/dashboard/tasksToday/TasksTodayType.ts, src/apis/dashboard/tasksToday/axios.ts, src/apis/dashboard/tasksToday/query.ts, src/apis/tasks/getTask/axios.ts, src/components/DashboardPage/DashboardTask.tsx, src/components/DashboardPage/DashboardTaskWrapper.tsx
- Task type별 리스트 조회 api 연결
- 프론트에서 상태 중에 postponed 를 서버 상태와 통일하기 위해 deferred 로 변경했습니다
close #179
=> [FEAT] Task type별 리스트 조회 api 연결

src/apis/instance.ts, src/apis/logout/logoutAxios.ts, src/components/SettingPage/LogOutBtn.tsx
- 로그아웃 시 localstorage를 지우고 로그인 페이지로 redirect 되도록 하였습니다.
- accessToken과 refreshToken이 둘 다 만료 또는 유효하지 않을 시 "로그인이 만료되었습니다. 다시 시도해주세요." 라는 alet이 뜨고 로그인 페이지로 redirect 되도록 코드를 수정하였습니다.
> 기록하며 개발하기!
- 
- 폴더구조 변경 혹은 더 추가로 로그인페이지로 리다이렉트가 필요한 부분이 있다면 말씀해주세요!
close #167 
https://github.com/user-attachments/assets/aa3fd34b-a468-4e2d-bdfd-281f72be0f33
=> [FEAT] 로그아웃 api 연결

src/apis/tasks/getTask/GetTasksResponse.ts, src/apis/tasks/getTask/query.ts, src/apis/tasks/updateTaskStatus/UpdateTaskStatusType.ts, src/apis/tasks/updateTaskStatus/axios.ts, src/apis/tasks/updateTaskStatus/query.ts, src/components/common/StagingArea/StagingArea.tsx, src/components/common/StagingArea/StagingAreaSetting.tsx, src/components/common/StagingArea/StagingAreaTaskContainer.tsx, src/components/targetArea/TargetArea.tsx, src/components/targetArea/TargetAreaDate.tsx, src/components/targetArea/TargetControlSection.tsx, src/components/targetArea/TargetTaskSection.tsx, src/pages/Today.tsx, src/types/today/TargetControlSectionProps.ts, src/types/today/stagingAreaSettingProps.ts
- Task 수정 api를 연결하였습니다.
- stagingArea <-> targetArea 드래그앤드롭 시 수정(Patch) api 호출 및 useMutation을 통한 Task 리스트 자동 업데이트 기능입니다.
> 기록하며 개발하기!
- useQuery에 `placeholderData` 사용 시 한번 불러올 때만 깜빡임이 심하고, 그 이후에는 기존에 캐시된 값으로 깜빡임을 최소화할 수 있다는 것을 알았습니다. 
- 드래그앤드롭 시 나타나는 찰나의(아마 Fetching동안) 다시 제자리로 돌아가는 부분 수정이 필요합니다. 지속적으로 개선중에 있지만 같이 고민해주시면 감사하겠습니다..!
close #174
=> [FEAT] Task 상태 수정 api (드래그앤드롭 부분 우선 구현)

src/App.tsx, src/components/common/BackGroundLayout.tsx, src/components/common/NavBar.tsx, src/pages/Login.tsx, src/pages/MainLayout.tsx, src/pages/NotFound.tsx
- 디바이스 화면 크기 대응을 위해 백그라운드를 설정했습니다
- 백그라운드 색상은 쌩블랙으로 설정했고, 
- 화면 border-radius 8px 로 설정했어요
> 기록하며 개발하기!
- 기존에 Navbar를 fixed로 만들어둬서 absolute 로 고치고 상위 컴포넌트에 relative 속성 주었습니다.
- 잘되나 봐주삼
close #208
=> [FEAT] 화면 백그라운드 설정

src/apis/timeBlocks/getTimeBlock/GetTimeBlock.ts, src/apis/timeBlocks/getTimeBlock/GetTimeBlockType.ts, src/apis/timeBlocks/getTimeBlock/axios.ts, src/apis/timeBlocks/getTimeBlock/query.ts, src/apis/timeBlocks/postTimeBlock/PostTimeBlockType.ts, src/apis/timeBlocks/postTimeBlock/axios.ts, src/apis/timeBlocks/postTimeBlock/query.ts, src/components/common/fullCalendar/FullCalendarBox.tsx, src/components/common/fullCalendar/processEvents.tsx, src/pages/Calendar.tsx, src/pages/Today.tsx, src/utils/getStartDayOfMonth.ts, src/utils/getStartDayOfWeek.ts
- Time-block 리스트 조회
- time-block data 가져오는 부분에 연결
> 기록하며 개발하기!
- data 가공하는 법에 대해 보다 더 잘 알게 되었습니다~~
- 캘린더 스타일 적용이 안됩니다..! 
close #193
=> [FEAT] Time-block 리스트 조회

src/apis/timeBlocks/postTimeBlock/PostTimeBlockType.ts, src/apis/timeBlocks/postTimeBlock/axios.ts, src/apis/timeBlocks/postTimeBlock/query.ts, src/components/common/fullCalendar/FullCalendarBox.tsx, src/pages/Today.tsx
- Task 타임블로킹 생성 api 연결
> 기록하며 개발하기!
- 10분이면 할 일을.. requestBody 변수명을 잘못 넣어서 시간을 많이 썼습니다. 명세를 잘 확인하자!
테스트 시 이 부분 참고해주세요!
close #212
=> [FEAT] Task 타임블로킹 생성 api 연결

src/components/common/fullCalendar/FullCalendarStyle.ts
- 풀캘린더 영역 넘어가는 이벤트 글자 처리를 하였습니다.
> 기록하며 개발하기!
- text-overflow: ellipsis; 를 하면 텍스트가 넘칠 때. ..으로 표시해줌을 알았습니다.
close #218
=> [FEAT] 풀캘린더 영역 넘어가는 이벤트 글자 처리

src/apis/timeBlocks/deleteTimeBlock/DeleteTimeBlockType.ts, src/apis/timeBlocks/deleteTimeBlock/axios.ts, src/apis/timeBlocks/deleteTimeBlock/query.ts, src/components/common/fullCalendar/FullCalendarBox.tsx, src/components/common/fullCalendar/processEvents.tsx, src/components/common/modal/Modal.tsx, src/components/common/modal/ModalDeleteBtn.tsx, src/components/common/modal/ModalDeleteDetail.tsx, src/components/common/modal/ModalHeaderBtn.tsx
- Task 타임블로킹 삭제 api 연결
> 기록하며 개발하기!
- fullcalendar에서 특정 이벤트 클릭 시 해당 이벤트의 info 내에서 taskId, timeBlockId 등의 상세정보 조회가 가능함을 알았습니다. 라이브러리가 확실히 데이터 연동을 쉽게 해주는 것 같습니다.
- 딜레이가 여전히 심합니다.. 개선방법이 필요해보입니다. 해당 부분 같이 고민해주시면 감사하겠습니다ㅜ
close #214
=> [FEAT] Task 타임블로킹 삭제 api 연결

src/components/DashboardPage/DashboardTask.tsx, src/components/common/BtnDate/BtnDate.tsx, src/components/common/BtnDate/BtnStagingDate.tsx, src/components/common/BtnTask/BtnTask.tsx, src/components/common/BtnTask/IconHoverContainer.tsx, src/components/common/ScrollGradient.tsx, src/components/common/StagingArea/StagingAreaTaskContainer.tsx, src/components/common/textbox/TextInputStaging.tsx, src/pages/DashBoard.tsx, src/pages/Today.tsx
- 불필요한 중간 time, date state 저장 삭제
- 모달 두개가 중복되어 하나 삭제
- 스크롤 그라디언트 스테이징 에리아에 추가함
- 태스크 추가 이름 비어있지 않을 때만 요청가게 함
- box-sizing 관련 스타일 문제있는지, 
- state 와 모달 삭제 구조 변경으로 인한 사이드이펙트 없는지 검토해주시면 감사하겠습니다
close #222
=> [BUG] 승연이의 짬뽕탕 (태스크 생성 기한 설정 모달 값 입력 이슈 & UI 수정사항 & 불필요한 값 삭제)

src/apis/timeBlocks/deleteTimeBlock/DeleteTimeBlockType.ts, src/apis/timeBlocks/deleteTimeBlock/axios.ts, src/apis/timeBlocks/deleteTimeBlock/query.ts, src/apis/timeBlocks/updateTimeBlock/PatchTimeBlockType.ts, src/apis/timeBlocks/updateTimeBlock/axios.ts, src/apis/timeBlocks/updateTimeBlock/query.ts, src/components/common/fullCalendar/FullCalendarBox.tsx, src/components/common/fullCalendar/processEvents.tsx
- Task 타임블로킹 수정 api 연결
- fullcalendar에서 re드래그 시, 이미 생성된 timeblock의 위치 옮길 시의 이벤트를 감지하여 api 실행되도록 구현
> 기록하며 개발하기!
- fullcalendar에서 re드래그 시, 이미 생성된 timeblock의 위치 옮길 시의 이벤트를 감지할 수 있음을 알았습니다. 라이브러리의 소중함을 다시 깨달았습니다.
- 수정이 된 후 딜레이가 있습니다. 이 부분 참고해주세요.
close #215
=> [FEAT] Task 타임블로킹 수정 api 연결

src/components/common/BtnTask/BtnTask.tsx, src/components/common/BtnTask/IconHoverContainer.tsx, src/components/common/StagingArea/StagingArea.tsx, src/components/common/StagingArea/StagingAreaTaskContainer.tsx, src/components/common/button/statusBtn/StatusStagingBtn.tsx, src/pages/Today.tsx
BtnTask 호버 완료버튼 뮤테이션 연결했습니다
-
- 명세에 따라 공사 예정
close #224
=> [FEAT] BtnTask 호버 완료버튼 뮤테이션 연결

src/components/common/fullCalendar/FullCalendarBox.tsx
- develop 충돌 해결 과정에서의 timeBlockId 삭제 에러 해결
- 충돌 해결 과정에서 삭제 id 시 timeBlockId 를 넘겨받지 못하는 오류가 생겼습니다.. 수정된 processEvents에 맞게 각 id의 상태를 다시 추가하여 해당 오류 수정하였습니다! 
> 기록하며 개발하기!
- 충돌 해결 시 유의하자. 
- TimeBlock 생성, 수정, 삭제 기능 한번씩 확인부탁드립니다.
close #228
=> [HOTFIX] develop 충돌 해결 과정에서의 timeBlockId 삭제 에러 해결

src/apis/timeBlocks/googleTimeBlock/axios.ts, src/apis/timeBlocks/googleTimeBlock/query.ts, src/components/common/button/RefreshBtn.tsx, src/components/common/spinner/Spinner.tsx
- 캘린더에서 동기화 버트을 누를 시 구글 캘린더에서 데이터베이스로 캘린더 일정이 동기화 돼서 동기화 후에 다시 캘린더 타임라인을 불러오도록 하였씁니다. 
> 기록하며 개발하기!
- useMuation에는 isLoading이 없어서 isPending으로 로딩 상태를 걸어 스피너를 추가하였습니다.
close #226 
https://github.com/user-attachments/assets/5a788b43-b2e1-4863-9d83-38e10712d656
=> [FEAT] 구글 캘린더 동기화 버튼 api 구현

src/apis/tasks/taskDescription/TaskDescriptionType.ts, src/apis/tasks/taskDescription/axios.ts, src/apis/tasks/taskDescription/query.ts, src/components/common/BtnTask/BtnTask.tsx, src/components/common/StagingArea/StagingAreaTaskContainer.tsx, src/components/common/fullCalendar/FullCalendarBox.tsx, src/components/common/modal/Modal.tsx, src/components/targetArea/TargetArea.tsx, src/components/targetArea/TargetAreaDate.tsx, src/components/targetArea/TargetTaskSection.tsx, src/pages/Today.tsx, src/types/today/TargetControlSectionProps.ts, src/utils/formatDatetoLocalDate.ts, src/utils/formatDatetoString.ts
- staging area와 target area에서 task 더블 클릭 시 상세 정보를 모달에 get 해오는 api를 연결했습니다.
> 기록하며 개발하기!
- 으,,앙 ㅜㅜ 너무 많은 걸 알게 되었고, 기존에 제가 작업하던 api 연결과는 많이 다른 부분이 있어 어제 오늘 대가리 깨며 많이 배운 것 같습니다,, 사실 아직도 많이 이해가 필요하지만, 그래도 비교적 쉬운 get 부분을 처음으로 작업하면서 내려주기만 하면 되는 부분이 대부분이라 감 잡는데 정말 많은 도움이 되었습니다. 제가 get 부분에 온전히 집중할 수 있도록 다른 부분을 작업해준 승연이에게 고맙습니다... 타입 에러 잡아준 지원이와 많은 질문을 받아준 성희도,, 사실 제가 한건 없더요 ㅜㅜ
- 옵셔널,, 을 많이 썼어요,, ㅋ
- - staging area에서는 targetDate가 없습니다. 요 부분이 좀 어려웠는데요, (왜냐면 staging area와 target area가 결국 modal이라는 같은 하위 컴포넌트를 공유하고 있기 때문에) staging area에서는 targetDate = null로 해주면서 해결하였습니다. 땡스 투 지원
- 원래는 time block에서도 상세 정보 모달이 노출되어야 하는데, 삭제 모달만 뜨는 것으로 수정되었습니다! 참고해주세요
- targetDate 타입에러 때문에 애를 먹었는데요, 과정에서 유틸함수에 string을 추가해주었습니다. 괜찮은지 한번 봐주시면 감사하겠습니다!
close #194 …
=> [FEAT] Task 상세 조회 api 연결

src/components/common/BtnDate/BtnDate.tsx, src/components/common/datePicker/DatePickerStyle.tsx
-  모달안에서 데이트픽커를 열 때 overflow:hidden으로 데이트픽커 모달이 사라져서 이를 수정하였습니다.
- 모달 안에서 dateBtn의 크기가 맞지 않아서 해당 내용을 수정하였습니다.
close #234
=> [FIX] 모달안에 datepicker 가려짐 수정

src/components/DashboardPage/DateArea.tsx, src/components/common/datePicker/DatePickerCustom.tsx
- endDate를 선택하기도 전에 placeholder에 값이 반영되어 startDate를 선택하는 즉시 placeholder가 비게 되어 안예쁜 이슈가 발생합니다.
- 현재는 모달에서 [확인]버튼을 눌러야먄 새로운 날짜값이 Placeholder에 반영됩니다. 따라서 placeholder가 비는 문제는 발생하지 않는데요, 어느 방법이 더 좋은진 모르겠어서 아래에 화면 녹화본 첨부 드립니다. 참고하여서 의견 알려주세요!!
- 그리고 과정에서 시간상의 이유로 지피티의 도움을 받았습니다. 따라서 무조건 어푸하는게 좋은 건 아닌 것 같아서 의견 여쭙니다!!
> 기록하며 개발하기!
-
- ex2
close #245 
https://github.com/user-attachments/assets/bcdafa92-5bfe-4cc5-952b-f05d32f8e7c5
https://github.com/user-attachments/assets/ac95cf68-ed76-470a-9ac6-8eadf54e9959
=> [FIX] placeholer 값 반영 수정

src/apis/timeBlocks/postTimeBlock/axios.ts, src/apis/timeBlocks/postTimeBlock/query.ts, src/apis/timeBlocks/postTimeBlock/timeblockType.ts, src/components/common/fullCalendar/FullCalendarBox.tsx, src/components/targetArea/TargetTaskSection.tsx, src/components/toast/Toast.tsx, src/components/toast/ToastContainer.tsx, src/components/toast/ToastContext.tsx, src/main.tsx, src/pages/Today.tsx, src/styles/GlobalStyle.tsx
- 일정을 클릭했을 때만 타임블록을 긁을 수 있도록 하였습니다
- 일정을 긁을 수 없는 곳을 긁을 때는 토스트 알림이 뜨도록 토스트를 구현하였습니다.
close #241 
https://github.com/user-attachments/assets/70a96072-5900-48df-a7ac-e833e7191b45
=> [FEAT] 풀캘린더 일정 선택 관련 기능 추가 

src/components/common/StagingArea/StagingArea.tsx, src/components/common/StagingArea/StagingAreaTaskContainer.tsx, src/pages/Today.tsx
- StagingArea에서 Task 모달 띄울 때 targetDate 넘기는 문제 해결
- 충돌을 해결하는 과정에서 targetDate 넘기는 부분이 다시 들어간 것 같습니다.
> 기록하며 개발하기!
- 충돌 해결할 때 유의하자. 
- 한번씩 상세조회 해주세요~~~ 
close #258
=> [HOTFIX] StagingArea에서 Task 모달 띄울 시 에러 수정

src/apis/tasks/createTask/query.ts, src/components/common/textbox/TextInputStaging.tsx
- 할 일 앤터로 입력 시 마지막 글자가 한 번 더 입력되는 버그 수정하였습니다.
> 기록하며 개발하기!
- 한글을 입력할 때만 마지막 글자가 한 번 더 입력되는 오류가 발생했는데 크롬 브라우저에서 한글을 사용하는 경우, 한글 입력 시 입력 중인 글자 아래 검은 밑줄이 생기는데 해당 밑줄이 있는 상황에서 키보드 이벤트 발생 시 이벤트핸들러가 두 번 호출 되는 문제가 존재한다고 합니다. 한글의 경우 자음과 모음의 조합으로 한 음절이 만들어지는 조합 문자이기 때문에 글자가 조합 중인지, 조합이 끝난 상태인지를 알 수 없기 때문에 발생하는 오류였습니다. 
- 해당 문제를  해결하기 위해 키보드 이벤트에 isComposing을 통해 입력 문자가 조합 문자인지 아닌지를 boolean값으로 반환하는 프로퍼티가 있었고 이를 통해서 조합문자일때만 이벤트를 호출하도록 코드를 추가하였습니다.
- `!e.nativeEvent.isComposing`
close #256
=> [HOTFIX] 할 일 앤터로 입력 시 마지막 글자가 한 번 더 입력되는 버그 수정

src/components/common/BtnDate/BtnDate.tsx
- 달력 모달이 안보이는 것이 아닌 보이지 않는 위치에 띄워짐을 알았습니다.
- 하여, 해당 위치 조정하였습니다.
- `size.type == 'long'` 인 경우와 아닌 경우로 나눠서 구분해두었습니다!  (`size.type === 'long'` 일때만 클릭됨을 고려함.)
> 기록하며 개발하기!
- 모달 위치 설정에 따라 모달이 보이지 않는 곳에 위치할 수도 있음을 알았습니다.
- 혹시 해당 모달이 다른 부분에서 쓰인다면, 추가 수정이 필요합니다! 본인이 퍼블리싱한 뷰에 해당 모달이 뜬다면, 꼭꼭 알려주세요!!
close #257
=> [HOTFIX] 달력 모달 위치 조정

src/apis/dashboard/tasksToday/query.ts, src/apis/tasks/updateTaskStatus/query.ts, src/components/common/BtnTask/TargetIconHoverContainer.tsx, src/components/common/button/TodayPlusBtn.tsx, src/components/common/button/settingBtn/SettingCheckBtn.tsx, src/components/common/button/statusBtn/StatusDoneBtn.tsx, src/components/common/button/statusBtn/StatusInProgressBtn.tsx, src/components/common/button/statusBtn/StatusTodoBtn.tsx, src/pages/Today.tsx
- BtnTask 에서 아이콘 호버했을 때 상태 변경하면 인벨리데이트쿼리로 쿼리키 통해 새로운 배열을 잡아와서 정렬이 되는데, 호버는 state로 관리하기 때문에 열린 상태에서 그대로 마우스를 벗어나 열린 채로 다른 위치로 이동하는 문제가 있었습니다.
- 뮤테이트 onSuccess 의 인밸리데이트쿼리 이후에 state 초기화 작업을 하도록 설정했습니다
- 대시보드쪽 플레이스홀더 지웠습니다
- 잘되는지봐주삼
close #259
=> [HOTFIX] 상태 변경 호버 지속상태 수정

src/components/common/fullCalendar/FullCalendarBox.tsx
- 구글캘린더 타임블록 정보 수정(위치이동) 막기
- 위치 이동, 타임블록 늘리기 or 줄이기 등의 이벤트를 취할 순 있지만, 구글캘린더 값은 고정된 상태로 있습니다.(바로 다시 되돌아갑니다.)
> 기록하며 개발하기!
- fullcalendar 라이브러리의 `info.revert();` 에 대해 알았습니다.
- 구글캘린더 변경을 막았습니다! 확인해주세요
close #268
=> [FEAT] 구글캘린더 타임블록 정보 수정(위치이동) 막기

src/apis/timeBlocks/updateTimeBlock/axios.ts, src/apis/timeBlocks/updateTimeBlock/query.ts, src/pages/Today.tsx, src/types/area/areaType.ts
- 타임블록 내에서 이동할 때 이동할 수 없는 곳이라면 토스트가 나오게 하였습니다.
- target에 있을 때만 타임블록을 긁을 수 있게 처리하였습니다 (staging에 있을때는 타임블록 못긁게 하였습니다)
close #271
=> [FEAT] 타임블록 안에서 일정 옮길 때도 토스트 알림

src/components/common/datePicker/DatePickerCustom.tsx
- 대시보드 뷰에서 지난 1주 전, 지난 1달 전 버튼을 클릭하면 placeholder에는 반영이 되고 아래 진행률 요약에도 반영이 되지만, datepicker 모달에 해당 날짜가 입력되지 않는 문제가 있었습니다. (미처 연동할 생각을 못함)
- 이를 데이트 피커에 반영해주었습니다~ 간단하게 useEffect를 사용해서 startDate와 endDate가 바뀔 때마다 반영되어 값이 변하게 해주었어요
> 기록하며 개발하기!
- 해당 placeholder가 있는 부분을 막바지에 급하게 수정하느라 지피티에게 도움을 많이 받았었는데 지금 다시 뜯어보려니 직접 썼던 코드를 일부 밀어버리고 지피티 코드가 대부분이었기 때문에 다시 읽어보는데 시간이 꽤 걸렸다. 아무리 급해도 내 코드를 직접 짜야겠다고 생각했다....
- 괜찮은가요? 
close #275 
`수정 전`
`수정 후`
=> [FIX] 대시보드 뷰 지난 날짜 버튼 클릭시 모달에 반영

.github/workflows/gradle.yaml, index.html
- maze 스크립트를 추가했습니다.
- 깃헙 시크릿에 키 넣어두고 야믈파일 cd단계에 env 추가해뒀습니다!
> 기록하며 개발하기!
- html 에서 env 가져와야 할 때 `%{env}%` 형태로 쓸 수 있습니다
- 가이드에는 env처리에 대한 내용이 없는데 일단 키값이니까 처리해 두었습니다
close #280
=> [CHORE] maze 스크립트 추가

src/assets/svg/index.ts, src/components/common/NavBarIcon.tsx, src/components/common/v2/IconButton.tsx, src/stories/Common/Button/IconButton.stories.tsx
- 공컴 아이콘 버튼 부분 제작했습니다
- 스토리북에 예시 아이콘 넣어뒀는데 icn_setting_어쩌고 이렇게 쓰여있는 형식 Screaming snake라고 린트에서 뭐라 해서... 수정하고 사용된 사이드바 부분 임포트 이름 수정했습니다.
> 기록하며 개발하기!
- 아이콘 stroke 색상 변경할 때 stroke 색상을 고정 색상에서 `currentColor` 로 변경하게 되면 기존에 사용하고 있던 색상을 따로 기입하지 않은 아이콘들에 문제가 생길 것 같아서.. 최대한 이부분을 변경하지 않고 styled(Icon) 처럼 받아서 변경하려고 했으나
- css 속성보다 인라인 스타일이 우선 적용되기 때문에 변경에 실패하고 currentColor 로 설정한 뒤 사용하는 방법 적용했습니다
- 또 Icon을 `ReactElement` type를 받게 만들었는데, 여기에 속성을 부여하기 위해서는 `cloneElement(Icon, { props: 'props1'});` 다음과 같이 설정해서 props 를 넘겨줄 수 있는 것을 알았습니다. 
- 기존의 요소를 복제하면서 요소에 새로운 props를 추가하거나 수정할 때 사용되고 기존 요소를 그대로 두고 props를 덮어쓰거나 병합할 수 있다고 합니다.
- 컴포넌트가 사이즈 분기, 아이콘 배경 부분, 아이콘 자체 색상 설정 부분으로 크게 세개로 나뉘어져 있습니다.
- Icon 부분에 지민언니 담당 부분인 아이콘을 넣어주어야 합니다!!  
- 스토리북에는 임시로 전에 사이드바 만들 때 썼던 아이콘을 넣어두었습니다. …
=> [FEAT] 공통 컴포넌트 아이콘버튼 퍼블리싱

src/components/common/v2/IconButton.tsx, src/components/common/v2/button/Button.tsx, src/components/common/v2/control/CheckButton.tsx, src/components/common/v2/control/DropdownButton.tsx, src/stories/Common/Button/Button.stories.tsx, src/stories/Common/Button/IconButton.stories.tsx
- 기존에 만들었던 공컴 드디어 아이콘 피알 머지해서 수정완 했슴니다.
> 기록하며 개발하기!
- 기존에는 아이콘을 `ReactElement` 타입으로 Button 에서 직접 받도록 설정했었는데요, 이번엔 아이콘명을 받도록 설정해봤습니다. 아이콘명 스트링 전달은 기존보다 초기 렌더링할 때 조금의 런타임 매핑 비용이 들지만(아이콘 뭔지 찾아야돼서) 리렌더링 최적화에는 더 좋다네요
- 대신 정해진 아이콘만 쓸 수 있으니가 유연성이 떨어질 수 있다는데.. 우리는 인덱스에 있는 것만 쓰니까 이게 더 명확할 것 같아요
- 이상한점 없는지 구조 괜찮은지 봐주심 감사하겠습니다 ( _ _)
close #304
=> [FIX] 기존 공통 컴포넌트 아이콘 수정

src/components/common/v2/TextBox/MainDate.tsx, src/components/common/v2/TextBox/SubDate.tsx, src/pages/Login.tsx, src/stories/Common/Button/MainDate.stories.tsx, src/stories/Common/Button/SubDate.stories.tsx, src/styles/colorToken.ts
- MainDate, SubDate 컴포넌트 퍼블리싱입니다.
- MainDate는 오늘 날짜일때만 `오늘` 버튼이 나타납니다. 
- SubDate는 props로 넘기는 type에 따라 색이 변합니다.
- storybook 추가했습니다.
> 기록하며 개발하기!
- **after 라는 것을 통해 쉽게 css만으로 밑줄 설정이 가능하다**는 것을 알게되었습니다. 
기능이 전혀 없는 보여주기용 밑줄이라 코드 적게 쓰고싶어서 찾아본건데.. 굉장히 유용한거같아요.
https://developer.mozilla.org/ko/docs/Web/CSS/::after
https://sookkiong.tistory.com/20 <- 참고링크
- SubDate는 각 행위(`default`, `hover`, `pressed`)에 따라 상태 바뀌는 핸들러를 하나로 합쳤습니다. **역할에 따라 그냥 하나하나 분리하는 게 좋을 지 봐주세요**
- 지금 제작중인 **TextBox부분 컴포넌트들에 들어가는 상태가 여러가지 있는데, 상수파일로 빼는 게 나을까요?** 은근 겹치는 게 없어서.. 일단은 각 파일마다 해당하는 상태 상수화 해놨습니다.
- 두 컴포넌트 모두 사용자가 입력하는 부분은 없어서 **날짜유효성검사는 따로 진행하지 않았습니다.** 
close #298 
**MainDate**
**SubDate**
=> [FEAT] MainDate, SubDate 컴포넌트 퍼블리싱

src/components/common/v2/button/Button.tsx, src/components/common/v2/dropdown/CalendarSettingDropdown.tsx, src/components/common/v2/dropdown/SortingDropdown.tsx, src/components/common/v2/dropdown/StatusDropdown.tsx, src/components/common/v2/dropdown/TimeDropdown.tsx, src/constants/sortType.ts, src/constants/statuses.ts, src/stories/Common/dropdown/CalendarSettingDropdown.stories.ts, src/stories/Common/dropdown/SortingDropdown.stories.ts, src/stories/Common/dropdown/StatusDropdown.stories.ts, src/stories/Common/dropdown/TimeDropdown.stories.ts, src/styles/shadow.ts, src/utils/generateQuarterTimes.ts
- 시간선택 드랍다운 컴포넌트 구현
- 할 일 상태 드랍다운 컴포넌트 구현
- 정렬 드랍다운 컴포넌트 구현
- 캘린서 설정 드랍다운 컴포넌트 구현
> 기록하며 개발하기!
- scrollbar의 커스텀을 진행하면서 `::-webkit-scrollbar`는 스크롤바 전체를 의미하고, `::-webkit-scrollbar-thumb`는 스크롤 바의 막대를 의미함을 알게되었습니다.
- `::-webkit-scrollbar-thumb`의 경우 padding이나 margin을 줄 수 없어서 `background-clip: padding-box; border: 4px solid transparent;`를 통해서 border를 투명한 색으로 주어 thumb과 track의 공간을 주었습니다. 
- `::-webkit-scrollbar-thumb`의 height는 직접 지정할 수 없고 스크롤되는 크기에 따라서 동적으로 적용되며 최소 길이 이상으로 줄일 수 없음을 알게되었습니다. => 스크롤할 내용이 많을 수록 스크롤바의 높이가 작아지고 스크롤할 내용이 적을수록 스크롤바의 높이가 길어진다!
- 피그마 상으로는 시간선택 드랍다운 컴포넌트가 divider가 있는 버전과 없는 버전으로 2가지인데 디자이너분께 해당 2가지 버전의 쓰임을 여쭤보니 다른 것 먼저 작업하라는 답변을 받아서 일단 divider가 없는 버전의 시간 선택 드랍다운만 만들었습니다.
- theme의 컬러코드가 피그마상과 차이가 있는 부분이 몇군데 있어서 (다 grey4인데 컴포넌트별로 색상차이가 있음) …
=> [FEAT] dropdown 퍼블리싱

src/apis/timeBlocks/postTimeBlock/query.ts, src/apis/timeBlocks/updateTimeBlock/query.ts, src/components/toast/Toast.tsx, src/components/toast/ToastContainer.tsx, src/components/toast/ToastContext.tsx, src/stories/Common/toast/Toast.stories.tsx, src/styles/color.ts, src/types/toastType.ts
- success, conflict, info 3가지 상황에 맞는 toast 컴포넌트 퍼블리싱을 하였습니다.
- 기존에 있던 toast 컴포넌트에 props로 code를 추가하여 code에 따라 아이콘과 배경색상을 변경하였습니다. 
> 기록하며 개발하기!
- 
- 기존의 theme에 orange 색상이 없어서 추가하였는데 추가하는김에 오렌지를 다 추가할까하다가 컴포넌트상에서 오렌지를 사용하는 게 orange5말고는 안보여서 디자이너 선생님들께서 다 사용하는 색상이라고 말씀해주시면 추후에 추가하고자 합니다.
- 이전까지 서버측에서 오류가 날 경우 code에 "conflict"를 담아서 보내주셔서 success, conflict, info로 코드를 정의하였습니다. 추후에 api관련 회의를 할 때 서버 측에도  success, conflict, info를 설명드리겠습니다!
close #313
=> [FEAT] Toast 컴포넌트 퍼블리싱

src/components/common/BtnDate/BtnDate.tsx, src/components/common/datePicker/CorrectionCustomHeader.tsx, src/components/common/datePicker/DateCorrectionModal.tsx, src/components/common/datePicker/DatePickerStyle.tsx, src/components/common/modal/Modal.tsx, src/components/common/textbox/TextInputStaging.tsx, src/components/common/v2/IconButton.tsx, src/components/targetArea/TargetControlSection.tsx, src/stories/Common/DateCorrectionModal.stories.tsx
- 데이트피커 모달을 만들었습니다
- 안에 인풋창이 없어져서 ref 제거했고
- 기존에 시간도 한 모달에서 관리했었는데 이부분이 사라져서 + 모달로만 날짜 설정할 수 있게 되어서 많은 상태를 제거했습니다.
- 수정해서 기존에 사용하던 곳에서 빌드 터지지 않게 수정했는데 기능 연결, 작동에 문제가 있을 것 같아요. 나중에 페이지+기능 연결할 때 잘 수정해야 할 것 같습니다
- 주간 글자쪽 테마가 피그마에 미지정되어있어 댓글로 문의한 상태입니다.
- 오늘 버튼 선택시 피그마 요구사항에 오늘이 포함된 날을 보이도록 하라고 되어 있었는데, 오늘 날짜를 선택하지 않고서는 해당 기능 구현이 어려워 현재 오늘 날짜가 선택되도록 한 후 피그마에 문의 댓글 남겨놓은 상태입니다.
close #318 
데이트피커 커스텀..햄드네요..
=> [FEAT] datepicker 모달 디자인 수정

src/components/common/Icon.tsx, src/components/common/fullCalendar/CalendarHeader.tsx, src/components/common/fullCalendar/CustomDayCellContent.tsx, src/components/common/fullCalendar/DayHeaderContent.tsx, src/components/common/fullCalendar/FullCalendarBox.tsx, src/components/common/fullCalendar/FullCalendarStyle.ts, src/components/common/fullCalendar/fullCalendarUtils.ts, src/components/common/v2/IconButton.tsx, src/components/common/v2/TextBox/MainDate.tsx, src/components/common/v2/popup/ClassificationBox.tsx, src/components/common/v2/popup/DeadlineBox.tsx, src/components/targetArea/TargetControlSection.tsx, src/pages/Today.tsx
- 캘린더 v2 디자인 반영
- 기존 일/주/월 -> 주/월 으로 캘린더 옵션 축소
- size에 따라 small -> 주 5일 캘린더, big -> 주 7일 캘린더로 변경
- 타임그리드 범위 조정 (30분 -> 15분)
> 기록하며 개발하기!
- fullcalendar 사용법에 대해 알게되었습니닷.
- 디자인 이슈 있는 지 확인 부탁드립니다 🙇‍♀️
close #322 
size = 'small'
size = 'big'
=> [FEAT] 캘린더 v2 변경

src/components/common/v2/TextBox/PopUp.tsx, src/components/common/v2/dropdown/TimeDropdown.tsx, src/components/common/v2/modal/MainSettingModal.tsx, src/components/common/v2/popup/DateBtn.tsx, src/components/common/v2/popup/DateTimeBtn.tsx, src/components/common/v2/popup/DeadlineBox.tsx, src/components/common/v2/popup/TimeBtn.tsx, src/stories/Common/dropdown/TimeDropdown.stories.ts, src/stories/modal/MainSettingModal.stories.ts
- 메인 세팅 모달 퍼블리싱을 하였습니다.
- DateBtn에 DateCorrectionModal을 연결하였습니다.
- TimeBtn에 기존의 TimeDropDown을 연결하였습니다.
> 기록하며 개발하기!
- onBlur를 활용해 컴포넌트 외부를 클릭했을 때 isOpen을 닫는 기능을 구현하였습니다
- 일단 모달 컴포넌트 내에서 상태가 수정되게는 하였으나 api붙이는 경우까지는 고려하지 않았습니다
- 수정하면 좋을 부분 말씀해주세요!!
close #325
<br/>
=> [FEAT] 메인 세팅 모달 퍼블리싱

src/apis/tasks/orderTask/axios.ts, src/pages/Today.tsx
- 순서 커스텀오더로 바꾸는 거 안되던 문제 수정
- post 에서 target 불린값 반대로 설정했던 점 + 서버에서 targetDate 파라미터 관련 필수로 지정했던 점(500에러) 등등 이 문제되어 이제야 잡았습니다..
- 잘 작동하는지 봐주세용
close #341 
근데 지원언니가 dnd 부분 갈아야 햇던 것 같은데 ...일단 api 쪽이니까 수정햇습니다
=> [BUG] custom order post api 연결 문제

src/components/common/BtnTaskContainer.tsx, src/components/common/StagingArea/StagingArea.tsx, src/components/common/StagingArea/StagingAreaTaskContainer.tsx, src/components/common/v2/TextBox/DumpingAreaBtn.tsx, src/components/common/v2/modal/DueDateModal.tsx, src/components/common/v2/popup/DateTimeBtn.tsx, src/components/common/v2/popup/DeadlineBox.tsx, src/pages/Today.tsx
- 전에 DueDate 모달 설정하던 브랜치 기준으로 브랜치를 팠습니다
- dumpingArea 특히 Todo 홀딩하는 부분 스타일링이 좀 이상해서 화면에 맞게 해두었는데 디자인 화면이랑 1000% 일치 하지는 않을 것 같습니다 추후 세세하게 수정해 볼게요 ...
- 드롭다운에서 시간 선택해서 연결하는 부분 구현해뒀습니다. 
- 기존 드롭다운에서는 `hh:mm am` 같은 형식으로 상태에 저장이 되어 있어서 뒤 am pm 부분만 잘라서 api 에 꽂았으니 이후에 이부분 건드리면 터질 수 있으니 주의해주세요
- 이 표시하는 부분들이랑 모달에서 표기하는 방법, state 로 관리하는 시간 형식이 다 string이다보니 제각각이라서.. 어디는 hh:mm am 이런 식으로 붙어있기도 하고 어디는 hh:mm 으로 되어있어서 이거 통일하고 변환하는 유틸 함수 만들기 + 출력값 형식 맞추기 함 해야 할 것 같아요 피알 올려두고 리뷰어푸까지 시간 걸릴테니 그때 해보겠습다
close #345
=> [FEAT] DueDate모달 2차 연결

src/components/common/BtnTaskContainer.tsx, src/components/common/StagingArea/StagingArea.tsx, src/components/common/StagingArea/StagingAreaTaskContainer.tsx, src/components/common/v2/TextBox/DumpingAreaBtn.tsx, src/components/common/v2/modal/DueDateModal.tsx, src/components/common/v2/popup/DateTimeBtn.tsx, src/components/common/v2/popup/DeadlineBox.tsx, src/pages/Today.tsx, src/utils/time.ts
진행사항 노티겸 피알 한번 씁니다 (성히언니 보삼)  
- DueDate 모달이 없어서 새로 만들었습니다
- 기존 큰 모달을 재활용하려고 했는데, 조건부 렌더링 부분이 너무 많아져서 너무 복잡해 따로 파는 게 나을 것 같아서 따로 빼서 제작했습니다
- create 하는 데에 필요한 state 들 만들고 연결했습니다
- 현시각 반영, 현재일로부터 14일 이후 등 반영했습니다
- Date 쪽 처리를 일단 시간이 없어 props 뚫어 가져갔는데 구조가 더러워서 조금 고민 중입니다.
- 말단 컴포넌트들 state 는 이제 필요없을 것 같아 차차 살펴보고 제거하고 싶습니다
- 구조가 컴포넌트에서 시간.날짜 상태 한번, 모달에서 시간,날짜 상태 한번, 전체 mutation 일어나는 곳에서 한번이라 상당히 복잡한데 , 모달 -> 전체에서는 모달에서 임시 상태를 가지고 있다가 표시해주고 또 취소하는 유즈케이스 대응하기 위해 필요합니다. 컴포넌트단은 한번 다시 봐야할 듯합니다
close #342
=> [FEAT] DueDate모달 연결

src/apis/timeBlocks/getTimeBlock/GetTimeBlockType.ts, src/apis/timeBlocks/getTimeBlock/axios.ts, src/apis/timeBlocks/getTimeBlock/query.ts, src/components/common/StagingArea/StagingAreaTaskContainer.tsx, src/components/common/datePicker/DateCorrectionModal.tsx, src/components/common/fullCalendar/CalendarHeader.tsx, src/components/common/fullCalendar/CustomDayCellContent.tsx, src/components/common/fullCalendar/DayHeaderContent.tsx, src/components/common/fullCalendar/FullCalendarBox.tsx, src/components/common/fullCalendar/FullCalendarStyle.ts, src/components/common/fullCalendar/processEvents.tsx, src/components/common/v2/TextBox/SubDate.tsx, src/components/common/v2/dropdown/CalendarSettingDropdown.tsx, src/components/common/v2/taskBox/Todo.tsx, src/components/targetArea/TargetTaskSection.tsx, src/hooks/useTodoEventHandler.ts, src/pages/Calendar.tsx, src/pages/Today.tsx, src/stories/Common/Button/Todo.stories.tsx
- 캘린더에 연결할 모달(미니캘린더, 조회필터링) 뷰 연결해두었습니다. (기능 추가는 api 나오면 진행 예정입니다!)
- src/apis/timeBlocks/getTimeBlock/ 파일들 수정
빠진 내용(: google calendar 연결) 코드 상에서 제외하였습니다. -> 이거때문에 캘린더 오류났던거!
- timeblock 스타일 수정하였습니다. ~~(월간 캘린더 스타일 수정은 올려두고 진행할게요) -> 수정 완료~~
- 캘린더 헤더 날짜와 실제 ref 값 안맞는 부분 수정하였습니다. 
- FullCalendar의 Draggable 기능 이용하여 todo박스 드래그앤드롭 통해 timeblock 생성 가능하도록 변경
-> 이제 dumping area / todo list 제한없이 timeblock 생성 가능!
- 드래그 시 todo박스가 다시 제자리로 돌아가는 현상, 드래그 스무스하지 못한 점 등은 해당 이슈에서 브랜치 새로 파서 반영할게요 🥺 
#350 
> 기록하며 개발하기!
- FullCalendar 드래그랑 react-beautiful-dnd 드래그랑 겹쳐서 사용 가능하다는 것 알게되었습니당
- 생성 시간대 등 오류 없는 지 확인 부탁드립니다! 
- 드래그 어색한 건 주말에 개선하겠습니다
close #336
=> [FEAT] timeblock 생성 기능+api 연결

src/apis/timeBlocks/getTimeBlock/GetTimeBlock.ts, src/components/common/fullCalendar/CalendarHeader.tsx, src/components/common/fullCalendar/FullCalendarBox.tsx, src/components/common/fullCalendar/FullCalendarStyle.ts, src/components/common/fullCalendar/processEvents.tsx, src/components/common/v2/dropdown/CalendarSettingDropdown.tsx, src/stories/Common/dropdown/CalendarSettingDropdown.stories.ts
- 상태(완료, 미완료, 진행중)에 따른 조회 필터링 기능을 추가했습니다
- 상태가 완료인 task의 timeblock은 스타일링이 달라서, 해당 부분도 추가하였습니다!
> 기록하며 개발하기!
- FullCalendar 클래스명 커스텀 방법
```ts
eventDidMount={(arg) => handleCompletedTask(arg)}
// 완료 task 스타일링 위한 클래스명 추가 (주간)
const handleCompletedTask = (arg: EventMountArg) => {
const weekElement = arg.el.querySelector('.fc-event-main');
if (weekElement && arg.event.extendedProps.isCompleted) {
weekElement.classList.add('completed');
}
};
```
- 서버측에 상태값 중 '진행 중' -> '진행중'으로 변경 요청해두었습니다! 
close #352
=> [FEAT] 조회 필터링 기능 추가

src/components/common/datePicker/DateCorrectionModal.tsx, src/components/common/fullCalendar/FullCalendarBox.tsx, src/hooks/useOutsideClick.ts
- 캘린더 헤더의 아이콘 클릭 시 띄워지는 미니캘린더 연결
- 기존엔 뷰만 연결해둬서 값 연결 및 외부영역 클릭 시 닫히도록 구현하였습니다.
- 외부영역 클릭 시 닫히도록 돕는 useOutSideClick 훅 생성 
> 기록하며 개발하기!
- 모달 외부영역을 굳이 컨테이너로 만들어주는 게 아니라(이걸 fixed로 만들며 따라오는 위치조절 불편함땜에..) 그냥 **모달 ref의 외부 영역 클릭 이벤트 발생 시 닫히도록** 하는 방법으로 있더라고요..! 훨씬 간단하네요
- https://jamong.tistory.com/7 블로그 참고
- 정상동작하는 지 확인해주세요!
close #359
=> [FEAT] 캘린더 내부 미니캘린더 기능 연결

src/apis/tasks/editTask/query.ts, src/apis/tasks/taskDescription/axios.ts, src/apis/tasks/taskDescription/query.ts, src/apis/tasks/updateTaskStatus/query.ts, src/components/common/StagingArea/StagingAreaTaskContainer.tsx, src/components/common/modal/Modal.tsx, src/components/common/v2/TextBox/PopUp.tsx, src/components/common/v2/control/DropdownButton.tsx, src/components/common/v2/modal/MainSettingModal.tsx, src/components/common/v2/taskBox/Todo.tsx, src/components/targetArea/TargetTaskSection.tsx, src/hooks/useInput.ts, src/pages/Today.tsx, src/stories/modal/MainSettingModal.stories.ts, src/types/tasks/taskType.ts
[feat: 태스크 상세 조회 api 연결](https://github.com/TEAM-DAWM/NUTSHELL-FE/commit/8d0e47f3786758e159b6161a5435b27d7ea6fb02)
[fix: useTaskDescription isopen 추가, 쿼리키 today 제거](https://github.com/TEAM-DAWM/NUTSHELL-FE/commit/fede4df899f303132afed0c1efe540a7f7901b83)
[feat: add onChange to PopUp](https://github.com/TEAM-DAWM/NUTSHELL-FE/commit/b0a284f6c099cca986b8e4f9f1cd2c287a84f25e)
[feat: useInput](https://github.com/TEAM-DAWM/NUTSHELL-FE/commit/2fcfe0a6d598c43cc993d1fb117dd8d8539ddc42)
[feat: add DetailedTaskType](https://github.com/TEAM-DAWM/NUTSHELL-FE/commit/00351b002e63468a41293fabd189a51c4540b592)
[feat: add description related apis](https://github.com/TEAM-DAWM/NUTSHELL-FE/commit/fb3ff2972c1083df22bd7e935640226ad60205b7)
[fix: change event type, link event to …
=> [FEAT] Task 상세 조회, 수정 기능 연결

src/apis/timeBlocks/postTimeBlock/query.ts, src/apis/timeBlocks/updateTimeBlock/query.ts, src/components/common/fullCalendar/FullCalendarBox.tsx, src/components/common/fullCalendar/FullCalendarStyle.ts, src/components/common/v2/modal/MainSettingModal.tsx, src/components/toast/Toast.tsx, src/constants/modalLocation.ts, src/stories/Common/toast/Toast.stories.tsx, src/types/toastType.ts
- 캘린더에 메인모달 연결
- 타임블록 드롭생성 시 자동으로 모달 열리고, 그 안에서 시간 지정하도록 설정
- 메인모달 위치, 진행시간 지정 여부 등에 따라 뷰 조정 
- response.code === 'conflict' 일 때 토스트 띄우기
- 토스트 타입 수정 ('info' -> 'conflict')
> 기록하며 개발하기!
- ㅜㅜㅜ
- 서버 측에서 사용자에게 보여야 할 오류 메세지는 'conflict'코드로 보내준다고 하여, 'info' -> 'conflict' 으로 변경하였습니다! 
- 드롭 생성 시 자동으로 열리는 모달이 드롭 위치를 기준으로 모달이 열려서, 위치에 있어 조금씩 차이가 납니다. 
- 드롭 생성 시 자동으로 새벽 12-1시 사이에 생성되는데, 만약 이 시간대에 이미 이벤트가 있다면 드롭으로 생성이 불가합니다(현재는)
요거 어케 고칠 지 서버+디쟌이랑 이야기해봐야합니다ㅜ
close #353
=> [FEAT] 캘린더 드롭 이벤트 생성 + 모달 타임블록 데이터 반영

src/pages/Login.tsx
- 별것은 아니고 창 사이즈 조절할 때 안예쁘게 줄어들어서 수정했습니다
- 정말 별 것 아님,, 내가 거슬려서 바꾸는 것임 죄송해요 다른 이슈는 못 고치겠음
> 기록하며 개발하기!
-
- ex2
close #384
https://github.com/user-attachments/assets/0f10647d-7df6-4419-8676-8932a3e4cf45
=> [FIX] 로그인 페이지 반응형 수정

src/components/common/StagingArea/StagingArea.tsx, src/components/common/v2/dropdown/SortingDropdown.tsx
적당한 데에다가 달았는데 얘는 클릭하면 그 옆에 뜨는 게 아니라서 걍 값으로 박았습니다.
근데 todo area 에서 또 연결한다 하면 고쳐야할듯
close #390
=> [FIX] staging area order 모달 위치

src/apis/timeBlocks/getTimeBlock/GetTimeBlock.ts, src/apis/timeBlocks/postTimeBlock/PostTimeBlockType.ts, src/apis/timeBlocks/postTimeBlock/axios.ts, src/apis/timeBlocks/postTimeBlock/query.ts, src/apis/timeBlocks/updateTimeBlock/PatchTimeBlockType.ts, src/apis/timeBlocks/updateTimeBlock/axios.ts, src/apis/timeBlocks/updateTimeBlock/query.ts, src/components/common/datePicker/DateCorrectionModal.tsx, src/components/common/fullCalendar/FullCalendarBox.tsx, src/components/common/fullCalendar/FullCalendarStyle.ts, src/components/common/fullCalendar/processEvents.tsx, src/components/common/modal/Modal.tsx, src/components/common/v2/modal/MainSettingModal.tsx, src/components/common/v2/modal/TimeBlockDeleteModal.tsx, src/components/common/v2/popup/DateTimeBtn.tsx, src/components/common/v2/popup/DeadlineBox.tsx, src/types/tasks/taskType.ts, src/utils/formatDateTime.ts
- TimeBlock post, patch api에 requestBody: isAllTime 추가
- 관련 TimeBlock 타입들에도 isAllTime 추가
- FullCalendar 종일이벤트 스타일링
- 메인 모달, 풀캘린더 값 연동
- 타임그리드 상에서(주간캘린더) 드래그 통해 종일이벤트 <-> 특정 시간대 이벤트 수정
- 메인모달 통해 종일이벤트 <-> 특정 시간대 이벤트 수정
> 기록하며 개발하기!
-
- 최대한 다 체크하긴 했는데.. 혹시 수정 중 에러터지는 동작 있는 지 체크 부탁드립니다! 
close #371
=> [FEAT] TimeBlock 종일이벤트 추가 

src/components/common/EmptyViewStaging.tsx, src/components/common/EmptyViewToday.tsx, src/components/common/StagingArea/StagingAreaTaskContainer.tsx, src/components/targetArea/TargetTaskSection.tsx
- 또 별거없는 사소한 피알
- 앰티뷰 두개 높이가 달라서 피그마 + 눈코딩으로 조정함!
- 피그마대로 위치 조정했는데 미세하게 안맞아서 눈코딩을 가미함 그래서 혹시 내 컴에선 이상하다 하면 알려주세요
- 별거 아니라 이상 없음 머지할게요
> 기록하며 개발하기!
-
- ex2
close #389
=> [FIX] 앰티뷰 위치 수정

src/apis/tasks/deleteTask/query.ts
- 태스크 지워지면 캘린더쪽도 지워져야 하는데 전에는 남아있어서 무효화 추가했습니다
- 근데 지금 allDay 인가 이슈로 400대 에러가 떠서 테스트를 못해봐서 .. 이거 적용하고 되는지 함 봐주셔요
close #368
=> [FIX] task delete 시 캘린더쪽 타임블럭쪽 쿼리키 Invalidate

src/components/common/NavBar.tsx, src/components/common/StagingArea/StagingArea.tsx, src/components/common/StagingArea/StagingAreaTaskContainer.tsx, src/components/common/fullCalendar/CalendarHeader.tsx, src/components/common/fullCalendar/FullCalendarStyle.ts, src/components/common/v2/TextBox/DumpingAreaBtn.tsx, src/components/common/v2/control/DropdownButton.tsx, src/components/common/v2/dropdown/StatusDropdown.tsx, src/components/common/v2/popup/DeadlineBox.tsx, src/components/common/v2/taskBox/Todo.tsx, src/components/targetArea/TargetArea.tsx, src/components/targetArea/TargetControlSection.tsx, src/components/targetArea/TargetFilterSection.tsx, src/components/targetArea/TargetTaskSection.tsx, src/hooks/useAuthRedirect.ts, src/pages/Login.tsx, src/pages/MainLayout.tsx, src/pages/Setting.tsx, src/pages/Today.tsx, src/styles/GlobalStyle.tsx
- 로그인한 유저일 경우 /today로 리다이렉트 시키는 로직 추가하였습니다.
- 디자인이 1920px * 1080px로 이루어져  대부분의 작업 환경인 맥북 13인치와 맞지 않아 font-size를 45%로 수정하고 height는 view height 기준으로 늘어날 수 있게 하였습니다.
- 쏟아내기 on/off에 따라서 캘린더의 width를 남은 화면을 꽉 채울 수 있도록 수정하였습니다.
- todo의 진행 상태를 수정하는 토글 영역 밖을 누르면 해당 모달이 꺼지도록 수정하였습니다.
- 모달의 마감기간 터치영역이 아이콘으로 한정되어 있어서 해당 터치영역을 넓혔습니다.
- 캘린더의 종일 부분의 테두리가 약간 맞지 않아서 해당 부분도 함께 수정했습니다. 
- 캘린더 상단 버튼들이 일직선으로 있지 않아서 해당 부분 스타일도 수정하였습니다.
> 기록하며 개발하기!
-
- 로그인 리다이렉트 관련 브랜치였으나 화면 크기가 맞지 않는게 너무 거슬려 함께 작업하였습니다 죄송함다.
- 간만에 한 캘린더 css 커스텀은 역시나 힘들었슴다. 코드가 몇개 수정되지 않았지만 찾는데 상당한 시간이 들었습니다 ,,
- 기본 폰트가 너무 작다고 생각되시면 말씀해주세요!! 
close #401 
- 캘린더 상단 버튼 정렬
- 데탑 뷰 크기 대응
https://github.com/user-attachments/assets/e871b0a0-063a-4db8-9b45-bc9644c98d9c
=> [FIX] QA 대응 - 로그인 리다이렉트 및 데탑 뷰 대응

src/apis/queryKeys.ts, src/apis/tasks/createTask/query.ts, src/apis/tasks/deleteTask/query.ts, src/apis/tasks/editTask/EditTaskDescriptionType.ts, src/apis/tasks/editTask/axios.ts, src/apis/tasks/editTask/query.ts, src/apis/tasks/getTask/query.ts, src/apis/tasks/orderTask/query.ts, src/apis/tasks/taskDescription/query.ts, src/apis/tasks/updateTaskStatus/query.ts, src/components/common/BtnTask/TargetIconHoverContainer.tsx, src/components/common/NavBar.tsx, src/components/common/StagingArea/StagingAreaTaskContainer.tsx, src/components/common/button/settingBtn/SettingCheckBtn.tsx, src/components/common/datePicker/DateCorrectionModal.tsx, src/components/common/fullCalendar/FullCalendarBox.tsx, src/components/common/fullCalendar/FullCalendarStyle.ts, src/components/common/v2/TextBox/DumpingAreaBtn.tsx, src/components/common/v2/modal/DueDateModal.tsx, src/components/common/v2/modal/MainSettingModal.tsx, src/components/common/v2/popup/DateBtn.tsx, src/components/common/v2/popup/DateTimeBtn.tsx, src/components/common/v2/popup/DeadlineBox.tsx, src/components/common/v2/taskBox/Todo.tsx, src/main.tsx, src/pages/Today.tsx
- task drag&drop 깜박임 해결
-  taskData를 새로운 배열로 생성하지 않고 기존 객체를 직접 참조함으로써 react query가 데이터가 동일하다고 판단하여 불필요한 리렌더링이 발생하지 않게 수정하였습니다. 
```
// 기존 코드
const updatedTargetData: TaskType[] = [...targetData];
const updatedStagingData: TaskType[] = [...stagingData];
// 수정 코드
const updatedTargetData: TaskType[] = targetData;
const updatedStagingData: TaskType[] = stagingData;
```
- task와 관련된 쿼리키를 정리하였습니다. 
- staging과 today의 task쿼리키를 분리하여 해당 영역에서 발생하는 삭제, 수정 작업의 경우 해당 영역의 쿼리키만 무효화하도록 하였습니다.
- task의 모달에서 상세 정보를 수정할 때 handleConfirm에서 handleStatusEdit(상태 변경)과 handleEdit(설명, 마감 기한 수정)이 동시에 실행되면서 비동기 작업 충돌이 발생하여 상태값이 제대로 변경되지 않고 있어서 비동기 작업이 순차적으로 일어날 수 있도록 코드를 수정했습니다.
> 기록하며 개발하기!
- 새로운 객체를 생성하면 react query는 데이터가 변경되었다고 판단하여 불필요한 리렌더링을 만들수도 있다는 점을 알게되었습니다.
- 상태관련 수정할 부분(타임블록 …
=> [FIX] task drag&drop 깜박임 해결 및 task 수정 로직 점검

src/apis/tasks/updateTaskStatus/query.ts, src/components/common/fullCalendar/FullCalendarBox.tsx, src/components/common/fullCalendar/FullCalendarStyle.ts, src/components/common/fullCalendar/processEvents.tsx
- timeblock 클릭 시 모달 오픈하는 과정에서 status가 하드코딩되어있길래 연동시켜두었습니다.
- **task status 변경 시 timeblock ui에 바로 반영**할 수 있도록 쿼리키 연동
- task 클릭 후 캘린더에 긁으면 이벤트가 바로 생성되는 과정에서, 아무 곳이나 클릭만 해도 해당 타임슬롯을 지정했다고 간주하고 이벤트 생성되길래.... 😑 너무 에러같아서 해당 동작 처리하는 **`addEventWhenDragged()` 에서는 15분짜리 이벤트 생성을 막아뒀습니다.**
- 타임그리드 클릭 할 때마다 06:00am으로 스크롤 초기화되는 게 ux상 너무 별로인 것 같아 **스크롤초기화 막아뒀습니다.**
- **timeblock 진행기간 수정 시 깜빡임 문제 해결**
- 캘린더 반응형 처리되도록 css 수정
> 기록하며 개발하기!
- timeblock 이동 시 깜빡이는 문제를 계속 쿼리쪽 문제라고 생각하고있었는데 `calendarEvents`가 `timeBlockData`를 기반으로 매번 재생성되면서 발생한 문제였다.. calendarEvents도 상태로 만들어서 즉각 반영 가능하도록 했습니다. 
- targetDate 연결하는 부분(캘린더내부 캘린더모달 등)은 말이 안되는 프룹스드릴링이 또 일어날거같아서 안했는데요.. 이 pr 올리고 전역상태로 바꾸는 작업을 진행해볼 예정이라 같이 손보겠습니닷. 일단 빠른 ut를 위해
close #407
=> [FIX] timeblock 및 calendar 반영 지연문제 해결 + UX개선

src/components/common/v2/TextBox/DumpingAreaBtn.tsx, src/components/common/v2/button/Button.tsx, src/components/common/v2/modal/DueDateModal.tsx, src/components/common/v2/modal/MainSettingModal.tsx, src/components/common/v2/popup/DateTimeBtn.tsx, src/hooks/useInputHandler.ts, src/utils/generateQuarterTimes.ts, src/utils/time.ts
- 쏟아내기 창 밑의 마감기한 모달 open/close 관련 클릭이벤트 개선
- 마감기한 모달의 '시간' 부분 데이터 UI연동 
- 마감기한 모달 오픈 시, 현재 시간을 15분 단위로 올림하여 표시
- 마감기한 모달 x 버튼 활성화
> 기록하며 개발하기!
- 임시로 박아둔 값들이 진짜 많이 고ㅣ롭히네요.,,,,
- 
close #411
=> [REFACTOR] 쏟아내기 및 마감기한 UX 개선

src/apis/tasks/editTask/query.ts, src/apis/tasks/taskDescription/query.ts, src/apis/timeBlocks/updateTimeBlock/query.ts, src/components/common/BtnTaskContainer.tsx, src/components/common/fullCalendar/FullCalendarBox.tsx, src/components/common/fullCalendar/FullCalendarStyle.ts, src/components/common/v2/TextBox/PopUp.tsx, src/components/common/v2/dropdown/TimeDropdown.tsx, src/components/common/v2/modal/MainSettingModal.tsx, src/components/common/v2/popup/DeadlineBox.tsx, src/components/common/v2/popup/TimeBtn.tsx, src/components/common/v2/taskBox/Todo.tsx, src/hooks/useInput.ts, src/hooks/useInputHandler.ts, src/stories/Common/dropdown/TimeDropdown.stories.ts, src/stories/modal/MainSettingModal.stories.ts, src/utils/formatTime.ts, src/utils/formatTimeWithAmPm.ts, src/utils/generateQuarterTimes.ts, src/utils/time.ts
- 모달 상세 내용 수정 완료 후, 모달을 닫았다가 다시 열면 이전 수정된 데이터가 반영되지 않고, 기존 데이터를 그대로 사용하는 문제가 발생했습니다.
- 기존 코드에서는 `TaskDetailFetched`와 `isOpen`만을 의존성 배열에 넣어서 `taskDetailData` 변경이 반영되지 않는 문제 발생했고,  `taskDetailData`를 의존성 배열에 추가하여, `taskDetailData`가 변경될 때마다 최신 상태로 반영하도록 수정했습니다.
- 추가적으로 조건문에 if (isTaskDetailFetched && taskDetailData)를 통해서 taskDetailData가 있을 때만 데이터를 설정하도록 수정했습니다.
- 이전 코드는 Promise를 직접 생성하여 mutate 함수의 onSuccess 콜백을 통해 Promise를 해결하도록 구현지만 부분적으로(캘린더에서 모달을 수정하는 경우) API 호출은 성공했지만 onSuccess 콜백이 호출되지 않아 handleStatusEdit함수가 호출되지 않는 상황이 발생하여 이를 해결하기 위해 mutateAsync를 사용하여  Promise가 명확하게 resolve되거나 reject되도록 할 수 있도록 하였습니다.
수정 전 코드
``` tsx
const { mutate: editMutate } = usePatchTaskDescription();
const handleEdit = async () => {
await new Promise((resolve) => {
editMutate(
{
taskId,
name: titleContent, …
```
=> [FIX] main setting modal 상태 관리

.github/workflows/test-link-deploy.yml
- PR단위마다 서비스 링크에 배포를 진행할 순 없으므로 팀 내(타 파트에게) 개발 진행상황 공유를 위해, develop 브랜치 내용과 연결되는 테스트링크를 배포했습니다.
- organization 레포 배포 시 발생하는 버셀 비용 이슈로,, 개인 레포로 포크떠서 배포 진행했습니다. 
(링크: https://shellin-client.vercel.app/)
- 개인 레포에 자동적으로 업데이트 하기 위해 cicd 설정해두었습니다. **develop에 푸시 시 발동합니다.**
```yml
on:
push:
branches:
- develop
```
- 항상 같은 내역을 유지하기 위해 배포용 레포에는 force push로 내역 업데이트합니다.
```yml
git push --force test develop
```
> 기록하며 개발하기!
- 버셀도 로그 확인하기가 굉장히 깔끔한 것 같습니다.
- 이런 cicd 설정 시 발생하는 커밋 작성자를 깃헙 봇(github-actions[bot])으로 설정할 수 있다는 걸 알게됐습니다!
- 현재는 서버에서 cors 등록 전이라, 로그인 화면까지만 접근 가능합니다! 구글로그인 버튼 누르면 cors 뜰거에요
- 더 추가하고싶은 설정 있다면 말해주세요!!
close #414
=> [CHORE] develop 브랜치 내역 자동 배포 CICD 설정

src/components/common/BtnTaskContainer.tsx, src/components/common/StagingArea/StagingArea.tsx, src/components/common/StagingArea/StagingAreaTaskContainer.tsx, src/components/common/fullCalendar/FullCalendarBox.tsx, src/components/common/v2/dropdown/TimeDropdown.tsx, src/components/common/v2/modal/MainSettingModal.tsx, src/components/common/v2/taskBox/Todo.tsx, src/components/targetArea/FilterSection.tsx, src/components/targetArea/TargetArea.tsx, src/components/targetArea/TargetTaskSection.tsx, src/pages/Today.tsx, src/stories/Common/Button/Todo.stories.tsx, src/stories/modal/MainSettingModal.stories.ts
-  mainSettingModal을 화면의 중앙에 뜨도록 수정했어요.
- stagingArea에서 열리는 모달의 경우 같은 모달을 호출함에도 뷰포트 기준 가운데에 뜨지 않았는데 해당 문제는 부모인 StagingAreaLayout이 `transform: translateX(-100%); `애니메이션을 적용받으면서 뷰포트가 아니라 StagingAreaLayout을 기준으로 모달이 배치되는 것 때문에 발생하는 문제였어요. 그래서 StagingAreaLayout이 transform을 사용하지 않고 대신 left를 이용하여 애니메이션을 적용하도록 수정했어요.
`width: ${({ isOpen }) => (isOpen ? '44.8rem' : '0')};`
-  mainSettingModal을 중앙에 뜨도록 수정하면서 기존에 모달 위치 정보를 위해서 필요했던 top, left를 제거했어요.
> 기록하며 개발하기!
- StagingAreaLayout에서 모달을 띄우면 가운데에 뜨지만 캘린더에 가려지는 문제가 발생했어요. Target에서는 아무 문제가 없었어서 문제점을 찾아보니 relative는 부모 요소의 z-index를 상속받기 때문에 부모 요소에 높은 z-index가 있으면 그 안에서 relative가 아무리 높아도 효과가 없기 때문이었스빈다. 그래서 `z-index: 1`을 지우면서 해결했어요. 이를 통해서 relative는 부모 요소의 z-index를 상속받는다는 것을 알게되었어용
- ex2
close …
=> [FIX] 모달 항상 중앙에 뜨도록 수정

src/apis/timeBlocks/postTimeBlock/query.ts, src/apis/timeBlocks/updateTimeBlock/query.ts, src/components/common/fullCalendar/FullCalendarBox.tsx, src/components/common/fullCalendar/FullCalendarStyle.ts, src/components/common/modal/Modal.tsx, src/components/common/v2/dropdown/CalendarSettingDropdown.tsx, src/components/common/v2/modal/MainSettingModal.tsx, src/components/toast/Toast.tsx, src/stories/Common/dropdown/CalendarSettingDropdown.stories.ts, src/utils/formatDateTime.ts
- 하루에 같은 테스크를 2번 이상 배치할 경우
- 이미 타임블록이 존재하는 곳에 테스크를 배치할 경우
-  모달의 타임블록 수정에서 conflict 발생 시 handleEdit 방지하도록 비동기 처리
추가적으로 자잘한 qa도 함께 진행했습니다. 
> 기록하며 개발하기!
- 기존의 timeblock및 모달의 함수들이 비동기처리가 되어있지 않아서 원하는 대로 동작하지 않던 부분들이 있엇습니다. 
역시 js는 비동기 처리,,,
- 확인하시고 타임블록 관련한 에러가 아직 남아있다면 말씀 부탁드려요!
close #421
=> [FIX] 타임블록 관련 QA 수정

src/apis/tasks/updateTaskStatus/query.ts, src/components/toast/Toast.tsx, src/components/toast/ToastContainer.tsx, src/components/toast/ToastContext.tsx
- revert 함수를 addToast 에 넣은 경우만 표시하도록 수정했습니다.
- 불필요한 함수 정리했습니다
```ts
const needRevert = updateData.status && updateData.status !== context.originalData.status;
```
updateData.status 가 있으며 이전과 같지 않은 경우에만 revert를 활성화합니다.
staging -> today, today-> staging 과 같이 움직이는 부분에도 status 업데이트 하는 콜이 null 을 넣어서 호출되고 있어서 일단 이렇게 적용했습니다.  
근데 모달에서 수정할 때 status 바꾸는 거랑 내용 바꾸는 거 api 를 따로 써서 status 를 바꾸면 되돌리기 텍스트가 무조건 뜹니다
> 기록하며 개발하기!
-
- 볼륨이 크다고 생각해 일단 이슈 닫기로 이야기되었었는데, 이부분 삭제 태스크 원복, 타임블럭 등 undo 어떻게 하면 좋을지 아이디어 있으시면 자유롭게 공유해주시면 감사하겟습니다.
close #420
=> [FIX] 토스트 undo 기능 있는 경우만 표시

src/components/common/datePicker/DateCorrectionModal.tsx, src/components/common/fullCalendar/FullCalendarBox.tsx, src/components/common/modal/ModalBackdrop.tsx, src/components/common/v2/modal/MainSettingModal.tsx, src/components/common/v2/popup/DateBtn.tsx
- **백드롭 색상을 추가 후, `MainSettingModal`에만 적용하였습니다.** 
- `isBackgroundColor` props를 옵셔널로 두어, 해당 props 추가 시 색상 적용됩니다.
- **메인모달 내부 모달(캘린더) 포지셔닝 (스크린샷 참고해주세요)**
- **모달 오픈 로직 전부 더블클릭으로 통일**
- 타임블록은 fullcalendar라이브러리의 event라서, `onDoubleClick`을 적용하지 못해서 '0.3초 내에 또다시 클릭 시 더블클릭으로 간주'하여 반영했습니다.
> 기록하며 개발하기!
- 풀캘린더 이벤트에 더블클릭을 달 순 있지만, fullcalendar에서 eventDoubleClick 등의 이벤트를 지원하지 않는 관계로 직접적인 dom조작으로 만 접근이 가능합니다. 0.3초 내에 다시한번 클릭 시 더블클릭으로 간주하도록 진행해도 충분히 자연스러움 & 이벤트 꼬이지 않게 접근 가능하네요
close #419 
메인모달 내부의 캘린더모달 위치입니다.
<p float="left">
</p>
=> [REFACTOR] 모달 포지셔닝 & 오픈로직 변경

src/pages/Today.tsx
- today 영역과 캘린더 영역 `selectedDate` 연동을 끊었습니다
- 전역상태 안넣었고 단순하게 `selectedDate`, `calenderSelectedDate` 으로 선택된 날짜 state 를 분리했습니다.
- 노션에는 오늘버튼 연동 끊기라고 되어있는데.. 날짜 이동하는 것도 끊어야 하는 것 맞죠?? 일단 끊어두었습니다.
selectedDate와 선택된 태스크 정보는 전체적으로 사용되는 것 같아 전역상태관리 넣어도 될 것 같아요..
따로 이슈파서 정리하면 좋을듯
close #426
=> [FIX] 캘린더 today 영역 오늘 버튼 연동 끊기

src/components/common/datePicker/CorrectionCustomHeader.tsx, src/components/common/fullCalendar/FullCalendarBox.tsx
- DateCorrectionModal 오늘 버튼 동작 정상화
> 기록하며 개발하기!
- fullcalender의 `ReactDatePickerCustomHeaderProps`에 change Month, Year 함수 통해 현재 보고있는 달력 뷰 조정 가능
- fullcalendar에서 오늘 기능은 없어도 뷰 조정 함수를 지원해줘서 저번 의논보다 굉장히 간단하게 끝났습니다~
close #428
=> [FIX] 캘린더 모달 오늘 버튼 동작 정상화

src/apis/timeBlocks/postTimeBlock/query.ts, src/apis/timeBlocks/updateTimeBlock/query.ts, src/components/common/v2/modal/MainSettingModal.tsx, src/components/toast/Toast.tsx, src/types/toastType.ts
- 기존 타임블록 충돌관련한 toast의 타입을 `conflict`에서 `info`로 수정하였습니다.
close #432
=> [FIX] 기존 toast의 타입 conflict에서 info로 수정
